### ISSUE TITLE
--whole-contig vs --per-contig

### ISSUE THREAD

**Issue by gresteban** [CGATOxford/UMI-tools#127]
Hi,

I've been reading the documentation and the different threads but there is an option that I cannot understand:

The description for the `--whole-contig` option has changed in the current version from 

> Read whole contig before outputting bundles: guarantees that no reads are missed, but increases memory usage.

to

> Consider all alignments to a single contig together. This is useful if you have aligned to a transcriptome multi-fasta.

From the latter, I find it confusing with the `--per-contig` option:

> All reads with the same contig will be considered to have the same alignment position.

Also, @IanSudbery states in #16:

> ...`--whole-contig` mode [...] assigns all reads on a contig to single position.

By their descriptions, `--whole-contig` seems redundant with `--per-contig` to me, so I would appreciate if you could clarify this option.

Finally, in post #44, @TomSmithCGAT comments regarding the `--per-contig` method that:

> ...this requires that the reads be aligned to a single contig, i.e a representative gene model.

Does it implies any special requirement or limitation when using this option?

Thanks in advance for your answer and for developing this software.

**Comment by TomSmithCGAT** [comment]
Hi @gresteban. Apologies for the confusion and thanks for binging up the discrepancy in the documentation.

To be clear, the `--whole-contig` option forces _dedup_ to parse an entire contig before yielding any reads for deduplication. This is the only way to absolutely guarantee that all reads with the same start position are grouped together for deduplication since we are working from the start position of the read, not the alignment coordinate on which the reads are sorted. However, by default _dedup_ read through another 1000bp before outputting read groups which will avoid any reads being missed with short read sequencing (<1000bp). See line 362 of [umi_methods.](https://github.com/CGATOxford/UMI-tools/blob/0.4.4/umi_tools/umi_methods.py#L362)

The `--per-contig` option makes _dedup_ ignore the alignment position for each read and only consider the contig to which it is aligned. This is useful for single-cell RNA-Seq techniques where the fragmentation occurs after amplification and hence two reads from the same initial molecule may align to slightly different positions on the same gene. In this case, one can align to the reference transcriptome and deduplicate using the contig only.

Given the above, the `--whole-contig` option should be described as:
>Read whole contig before outputting bundles: guarantees that no reads are missed, but increases memory usage

It looks like I added the erroneous documentation regarding the `--whole-contig` option about a year ago (28f8757). This documentation may also have contributed to @IanSudbery  suggesting the use of the `--whole-contig`when he meant `--per-contig`

From version 0.4 onwards (r[elease notes](https://github.com/CGATOxford/UMI-tools/releases/tag/0.4.0)), we've added further options for deduplication in a gene-orientated manner. My point above from #44 was that the `--per-contig` option will not work if you align to a transcriptome containing multiple transcripts per gene since two reads from the same molecule could conceivable be aligned to different transcripts (contigs). To remedy this we've included the `--per-gene` and `--gene-transcript-map` options which allow you to specify which transcripts come from which genes. 

I assume from your questions regarding the `--per-contig` option that you're using UMI-tools for single-cell RNA-Seq? If so, keep an eye out for the release of version 0.5. We're planning some fairly major improvements for scRNA-Seq analyses.

**Comment by IanSudbery** [comment]
Sorry if i've caused confusion by suggesting the wrong option.

**Comment by gresteban** [comment]
Thanks for all the detailed explanations, it's clear now. Maybe, the `--whole-contig` option could be recommended for long-read sequencing only in the documentation, mentioning the 1000bp limit.

I'm aware of the new options that you're implementing for version 0.5 and I'm already subscribed to the corresponding threads to be updated with their progress. For the moment, `--per-contig` seems exactly what I need since my reads were generated with a protocol like the one that you describe and I have them mapped on a transcriptome coming from the annotated genome, so no more than one transcript per gene.

Thanks again for your responses and the good work.
