### ISSUE TITLE
Dedup question

### ISSUE THREAD

**Issue by leleonp** [CGATOxford/UMI-tools#129]
First at all, thanks for this very nice tool!!!
Second, I just wondering how the _dedup_ for paired-end sequencing works?
It takes into account the UMIs of 5' and 3' together to remove the reads, or only take into account
one end (5' or 3')?
Thanks in advance
Best regards

**Comment by TomSmithCGAT** [comment]
Hi @leleonp. For paired-end sequencing, if the UMI is split across the two reads, we expect the two UMsI to be concatenated and this concatenated UMI attached to the end of both read pairs. This way, the two UMIs are considered together in the downstream deduplication. This can be performed with _extract_ with the `--split-barcode`, `-bc-pattern2`, `--read2-in` and `read2-out` options.

In the downstream deduplication, for single end sequencing we use just the start position of the read to determine the groups of reads which may be duplicates. For paired end sequencing (option '--paired'), we also use the template length so that the read pairs must have the exact same alignment position.

**Comment by tooba65** [comment]
I have used the `--paired` option in the `umitools dedup`. I would expect that the output bam file would have an equal number of read1 and read2 (output of `samtools flagstat`).
I'm a bit confused with the results as the number of read1 and read2 are equal before using umitools.
Would you please clarify this for me?
Thank you in advance!

**Comment by IanSudbery** [comment]
Hi tooba65, can you clarify what your question is? Under most circumstances, if a read1 is output, then a single copy of the corresponding read2 is output. Are you saying that the number of read1s and read2s is not equal after deduplication?

There are two circumstances under which this can happen, and it depends on a combination of how BAM files encode pairing information and how mappers output read pairs. 

### Circumstance 1: Two alignments for read2

The SAM specification says that the pairing information is recorded by recording the chromosome and position of the *primary* alignment of the mate read. Now imagine you have a read pair where the read1 has a single alignment position and the read2 has two alignment positions. Some mappers will output the read1 only once, because it has only one alignment position, but other aligners will output two identical copies of read1, marking one as primary and one as secondary - this maintains an equal number of read1 and read2s. However, both read1s will point to the primary alignment of read2 - no read1 will point to the secondary alignment of read2 (some aligners break this rule, but by no means all). So you have a situation like:

```
    read1.p ---> read2.p
             ____/
    read1.s /    read2.s
```
Because UMI-tools makes its decisions on the basis of read1 (including the information stored in read1 on the position of read2), and then finds the read2 mates of the read1s it decides to keep, only one of the read2s will be output.  ACtaully, I can't imagine any different way in which we might operate that would output both read1s and both read2s. 

### Circumstance 2: Two alignments for read1

If there are two alignments for read1, then the situation is a little more complex. Again, both read1s (whether primary or secondary) will point to the same read2. When UMI tools decides to keep a read1, it adds the details of the read2 it is look for to a set. When to comes across read2s, it checks against its list of things its looking for to see if it should be output, and if it is there, it outputs the read *and then deletes it from the list*. This keeps memory usage reasonable. If, when a chromosome is finished, not all the read2s have been found, it scans the chr again from the start to find the read2's its missing. 

Now imagine read1 primary alignment is selected, and then read2 primary alignment is found - at this point read2 primary alignment is removed from the "looking for list". Now read2 secondary alignment is selected and added to the list. read2 primary alignment will be output again on the second sweep (read2 secondary alignment will never be output because no read1 points to it) - thus read2 primary alignment is output twice. 

Now image read1 primary alignment is selected, and then read1 secondary alignment is found. read2 primary is already on the list. now read2 primary is found and removed from the list. - both read1s have been output, but only 1 read2. 

This second problem may be theoretically soluble and we are working on it.

**Comment by juheon** [comment]
Hi IanSudbery, I am a bit confused.
For Circumstance 1, if the primary/secondary alignment positions of read 1 are the same but the primary/secondary alignment position of read2 are different, the primary/secondary alignments of read1 will point to primary/secondary alignment of read2, respectively. Isn't it? This is because of different alignment positions of read2 primary/secondary alignment (TLEN of read1 alignment can be used to find its read2 alignment position). If then for Circumstance 1, both primary/secondary alignment of read2 will be printed after deduplication.

**Comment by IanSudbery** [comment]
> if the primary/secondary alignment positions of read 1 are the same but the primary/secondary alignment position of read2 are different, the primary/secondary alignments of read1 will point to primary/secondary alignment of read2, respectively. Isn't it?

No, or at least not according to the SAM format specification. Which states that that RNEXT and PNEXT fields should always point to a primary alignment:
> 7. RNEXT: Reference sequence name of the primary alignment of the NEXT read in the template. For
the last read, the next read is the first read in the template.

> 8. PNEXT: 1-based Position of the primary alignment of the NEXT read in the template.

Now not all aligners actaully follow the SAM spec, and some will us the scheme you suggest, but others do follow the SAM spec and the RNEXT and PNEXT fields of the secondary alignment of read1 will point to the primary alignment of read2.
