### ISSUE TITLE
Doubt: `multimapping-detection-method`  flag

### ISSUE THREAD

**Issue by k3yavi** [CGATOxford/UMI-tools#135]
Hi guys,

I was wondering what's the default behavior of `umi_tools extract` w/o `multimapping-detection-method` flag?
Basically, say I have a multi-mapped SAM file on txptome and I use following two commands:
```
umi_tools dedup -I <INPUT> --multimapping-detection-method NH --per-gene --gene-transcript-map=<GENE_TXP_MAP> -S <OUTPUT>
```
```
umi_tools dedup -I <INPUT> --per-gene --gene-transcript-map=<GENE_TXP_MAP> -S <OUTPUT>
```
Do we expect different `<OUTPUT>` files? If yes, does that mean for the first case, it is just like `--per-contig` option i.e. selecting randomly one txp for each gene? and how are we resolving multi-mapping?

Also I saw that you have mentioned about `umit_tools count` command in some earlier issue. So, if I want absolute count values at gene level would replacing dedup by count is the right command to use?

Finally the last question, if I have mapped the reads to genome (instead of transcriptome earlier) what's the recommended way of generating gene level count? is it using `umi_tools dedup` followed by `htseq/feature_count`?

Thanks!

**Comment by TomSmithCGAT** [comment]
Hi Avi.

The multimapping detection method is just used to select one 'best' read for each UMI at each position. By default, the read with the highest MAPQ is selected. If you supply a multimapping detection method, the read with the fewest mappings is selected. 

We've decided not to resolve multimapping reads since there are many ways to handle multimapped reads with UMIs depending on the particular application. Instead, it's up to the user to decide whether to include multimapped reads in the BAM they supply to UMI-tools. Unfortunately, selecting one read at each position can lead to odd results for multimapping reads so I'd suggest excluding these reads. If the user does want to include multimapped reads, I'd suggest using the _group_ command since this will mark each read at each position with the group to which it has been assigned. The user can then decide how to deduplicate the reads based on their mapping locations and groups. 

If you want absolute counts at the gene level, I'd definitely recommend using the _count_ command. We're just finishing off the final updates to count before we release the next update. 

In answer to your last question, yes, you can use either htseq or featureCounts to tag each read with the gen to which they have been assigned, and then `umi_tools count` using the options to define how the gene is encoded in the BAM tags. The next release will also include a `umi_tools count_tab` command to take in a flatfile containing two columns, read name and gene_id which can be output from featureCounts/htseq.

**Comment by k3yavi** [comment]
Thanks @TomSmithCGAT .
