### ISSUE TITLE
Selecting a random read as representative for a bundle

### ISSUE THREAD

**Issue by tomsing1** [CGATOxford/UMI-tools#15]
I believe the following code snipped from _dedup_umi.py_ shows how a random representative read is selected for a bundle when there is a tie for mapping quality.
```
read_counts[pos][key][umi] += 1
prob = 1.0/read_counts[pos][key][umi]
if random.random() < prob:
    reads_dict[pos][key][umi]["read"] = read
```

Yet, if I understand correctly, the ```read_counts[pos][key][umi]``` counter is not reset afterward and continues to accumulate counts in case other copies of the same molecule are encountered. 

Wouldn't that lead to lower probabilities of replacing the representative read with the current one as the analysis progresses? Am I misunderstanding the logic?

**Comment by IanSudbery** [comment]
At any given execution the chance of replacing the current read with the new read is reduced, yes. But averaged over the whole process the probabilities of any given read ending up as the representative one is equal, because earlier reads must be selected multiple times. 

Consider a simple situation, in which there are three reads. 
When the first read is found, it is selected as the representative read. 
When the second read is found, there is a 1/2 chance the first read will remain the representative read and 1/2 chance the new read will be selected:

```
P(X_2 = read2)= 1/2
P(X_2 = read1)= 1 * P(X_2 != read2)) = 1 * (1 - P(X_2=read2))= 1* (1-1/2) = 1/2
```

where X_n is the representative read when the nth copy of the read is encountered.

When the third read is encountered, there is a 1/3 chance it will replace the current read. Thus the probabilities are:

```
P(read3) = 1/3

P(read2) = P(X_2 =  read2) * P(X_3 !=read3) 
         = P(X_2 = read2) * (1-P(X_3=read3)) 
         = 1/2 * 2/3 
         = 1/3

P(read1) =  P(X_2 =  read1) * P(X_3 !=read3) 
         = P(X_2 = read2) * (1-P(X_3=read3)) 
         = 1/2 * 2/3 
         = 1/3
```

if a fourth read were found, then the probabilities would be:

```
P(read4) = 1/4

P(read3) = P(X_3 = read3) * P(X_4 != read4) 
         = P(X_3 = read3) * (1 - P(X_4 = read4))
         = 1/3 * 3/4
         = 1/4
```

and so on. 
Thus the chance of all reads ending up as the representative one is equal, without having to remember all the reads.

**Comment by tomsing1** [comment]
Thanks a lot for the great explanation!
