### ISSUE TITLE
problems using dedup_umi.py (method = adjacency)

### ISSUE THREAD

**Issue by KaiyangZ** [CGATOxford/UMI-tools#16]
Hi, 
I got a couple of problems with I was using dedup_umi.py to handle a set of single-end scRNAseq reads ( I used the method "adjacency"), I would be very grateful if you would help me with them:
1. it is reported "Number of reads out: 34903" in the stdout log, but in my output bam file, there are actually 55847 reads, do you have any idea why they don't match?
2. it seems that there are still duplicate reads in the output, i.e:
HISEQ1:340:C7K5CACXX:2:2209:17010:36435_GGAATT  16      1       629266  255     3S41M   *       0       0       AGACTAGTTCGGACCTCCCTGTTCTTATGAATTCGAACAGCATA    FFHHHHHJJIIHFJIIJJJIJJJJJJJJJJJJJJJJIJJJJIHH    NH:i:1  HI:i:1  AS:i:36 nM:i:2

HISEQ1:340:C7K5CACXX:2:1109:1824:92364_GGAATT   16      1       629266  255     3S41M1S *       0       0       AGACTAGTTCGGACCTCCCTGTTCTTATGAATTCGAACAGCATAG   JJJJJJJJJJJJHJJJJJJJJJIJJIJJJJJJJJJJJJJJJJHHF   NH:i:1  HI:i:1  AS:i:36 nM:i:2

these two reads with the same UMI and same mapping position are both retained in the output...

Could you please help me to figure out these two issues? Thank you very much in advance.

Kaiyang

**Comment by TomSmithCGAT** [comment]
Hi Kaiyang,

Would you be OK to email me a pre-deduplication BAM with just reads at this position. I can have a look at what's going on here.The only difference I can see between those alignments is that one has been softclipped by an additional base, though that I wouldn't expect that to cause a problem. I'll have a look at the logging of outputted reads out at the same time.

Tom

Tom Smith, PhD
CGAT Training Fellow | http://www.cgat.org<https://owa.nexus.ox.ac.uk/owa/redir.aspx?C=tg_bDY9IpU-WsZT9DRtecLrzBQBo5dAIR2VtNMFUhhmiSbB621cWM1yWzPrEKkt2W6Kx2kZl0Lg.&URL=http%3a%2f%2fwww.cgat.org>
MRC Functional Genomics Unit | University of Oxford
+44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk
https://cgatoxford.wordpress.com/author/tss505/
________________________________

**Comment by IanSudbery** [comment]
Hi, 

I can see what is happening in both cases. 

Firstly, the read logging is just wrong. It appears that we are logging positions output rather than reads output. That is easily fixed.

The second issue is more interesting. 

The difference between the two reads is indeed the softclipped base at the end of the CIGAR string. These reads are on the reverse strand. Thus the end of the CIGAR string is the start of the read. Thus in the second read the first base of the read has been softclipped. When deduplicating, dedup_umi uses the position of the first base in the read, not 5' most base of the alignment (ie the BAM pos field). Thus dedup_umi calculates the start positions of these reads as:629307 and 629308 respectively. 

It is informative to ask where that G might have come from. 
* On the 3' end of a read it could be an untrimmed adapter base, but this is unlikely on the 5' end.
*  It could be that this read is sitting on an exon boundary, and the G belongs on the other side of the boundary, in which case the "true" start position of the second read would be neither 629307 or 629308, but it would still be a different start position from the preceding read.
* The other alternatives are that it is either a mismatch, or a sequencing error, and thus the correct position would be 629308 (i.e. different from the preceding read).

However, it seems unlikely that two adjacent reads of independent biological origin should have the same UMI. 

**_Can I ask what protocol you were following for your scRNAseq?_** In particular, is the fragmentation step before or after PCR? Many scRNAseq protocols, particularly those that use UMIs, fragment the cDNA after UMI addition and PCR, and in this case the genome mapping position is not useful for determining the uniqueness of a read because different PCR copies of the same biological molecule could fragment in different places. The usual practice in this case is to map to the transcriptome, using the gene id as the contig. dedup_umi can then be run in --whole-contig mode, which assigns all reads on a contig to single position. Perhaps we could do with a script to assign reads to genes for people that would rather map to the genome?

**Comment by KaiyangZ** [comment]
Hi Tom and Ian,
Thanks a lot for your reply.
We were following the single-cell tagged reverse transcription (STRT) protocol, where the amplified cDNAs are "fragmented"  and tagmented using Tn% transposase carrying a well-specific barcode. In theory, the reads from different PCR copies should all start from the 5'end of the original mRNA molecule. So I think in this case, the genome mapping position should be used in determining the uniqueness.
A pre-deduplication bam with just reads at this position is attached. All the reads at that pos are attached with the same UMI and only one read was softclipped by an additional G. Is it more likely a sequencing error? 
Best regards,Kaiyang
 

    On Monday, March 14, 2016 12:16 PM, Ian Sudbery <notifications@github.com> wrote:
 

 Hi, I can see what is happening in both cases. Firstly, the read logging is just wrong. It appears that we are logging positions output rather than reads output. That is easily fixed.The second issue is more interesting. The difference between the two reads is indeed the softclipped base at the end of the CIGAR string. These reads are on the reverse strand. Thus the end of the CIGAR string is the start of the read. Thus in the second read the first base of the read has been softclipped. When deduplicating, dedup_umi uses the position of the first base in the read, not 5' most base of the alignment (ie the BAM pos field). Thus dedup_umi calculates the start positions of these reads as:629307 and 629308 respectively. It is informative to ask where that G might have come from.    
   - On the 3' end of a read it could be an untrimmed adapter base, but this is unlikely on the 5' end.
   -  It could be that this read is sitting on an exon boundary, and the G belongs on the other side of the boundary, in which case the "true" start position of the second read would be neither 629307 or 629308, but it would still be a different start position from the preceding read.
   - The other alternatives are that it is either a mismatch, or a sequencing error, and thus the correct position would be 629308 (i.e. different from the preceding read).
However, it seems unlikely that two adjacent reads of independent biological origin should have the same UMI. Can I ask what protocol you were following for your scRNAseq? In particular, is the fragmentation step before or after PCR? Many scRNAseq protocols, particularly those that use UMIs, fragment the cDNA after UMI addition and PCR, and in this case the genome mapping position is not useful for determining the uniqueness of a read because different PCR copies of the same biological molecule could fragment in different places. The usual practice in this case is to map to the transcriptome, using the gene id as the contig. dedup_umi can then be run in --whole-contig mode, which assigns all reads on a contig to single position. Perhaps we could do with a script to assign reads to genes for people that would rather map to the genome? —

**Comment by IanSudbery** [comment]
Hi Kaiyang,

The STRT-umi protocol says that non-template Gs are added to the 5' end of the reads, between the UMI and the start of the cDNA, and that they trim a maximum of 9 of these off. Have you trimmed these off? If so, this could be a rare read with 10 non-template Gs on the start.

**Comment by KaiyangZ** [comment]
Hi Ian,
yes, exactly, this should be the reason. I also trimmed maximum of 9 Gs following UMIs off. Now I will remove all successive Gs following the UMIs and check the result. There should be no harm even if the template Gs are removed, in which case the start positions of all reads from the same molecule will be shift the same number of bases right. Thanks again for your help.  

    On Monday, March 14, 2016 3:46 PM, Ian Sudbery <notifications@github.com> wrote:
 

 Hi Kaiyang,The STRT-umi protocol says that non-template Gs are added to the 5' end of the reads, between the UMI and the start of the cDNA, and that they trim a maximum of 9 of these off. Have you trimmed these off? If so, this could be a rare read with 10 non-template Gs on the start. —

**Comment by KaiyangZ** [comment]
Hi Ian,
I rechecked the reads file after trimming, the additional G in the second read is actually a C at 5' end of the read (as the read mapped on the reverse strand), so it cannot be the non-template Gs...  

    On Monday, March 14, 2016 3:46 PM, Ian Sudbery <notifications@github.com> wrote:
 

 Hi Kaiyang,The STRT-umi protocol says that non-template Gs are added to the 5' end of the reads, between the UMI and the start of the cDNA, and that they trim a maximum of 9 of these off. Have you trimmed these off? If so, this could be a rare read with 10 non-template Gs on the start. —

**Comment by IanSudbery** [comment]
Sorry for letting the ball drop on this. Did you mange to sort your problem? I'm not sure it really makes sense for these reads to be marked as duplicates because they have different sequences at the 5' end of the read (I might be more inclined if they were at the 3' end) but I suppose we could make it an option.

**Comment by KaiyangZ** [comment]
Hi lan,
I kept them as reads from distinct molecules, but I am wondering what is the reason for considering the the start position of a read to be the start of its alignment minus any soft clipped bases instead of simply the start of the alignment. 
Thank you very much.
Kaiyang 

    On Wednesday, March 23, 2016 11:39 AM, Ian Sudbery <notifications@github.com> wrote:
 

 Sorry for letting the ball drop on this. Did you mange to sort your problem? I'm not sure it really makes sense for these reads to be marked as duplicates because they have different sequences at the 5' end of the read (I might be more inclined if they were at the 3' end) but I suppose we could make it an option. —

**Comment by TomSmithCGAT** [comment]
Hi Kaiyang. To quote Ian's original response, "When deduplicating, dedup_umi uses the position of the first base in the read, not 5' most base of the alignment (ie the BAM pos field).", hence the identification of soft-clipped bases.

The reason for this is that two reads could have the same alignment position but have different true start positions. Imagine we have two rna-seq reads from the same transcript where Read 1 starts at the 5' base of Exon 2 and Read 2 starts at the 3' base of Exon 1. In the mapping, the alignment for read 1 will correctly start at the 5' base of Exon 2. The 5' base of Read 2 will be soft clipped off as a 1bp anchor is insufficient to split the read across the intron. The Read 2 alignment will thus start at the 5' base of Exon 2, as per Read 1. So, in this instance, we have two reads with the same alignment start position in the BAM file, but different true start positions. For this reason, the soft clipped bases are used when determining which reads share the same start position.

**Comment by TomSmithCGAT** [comment]
@KaiyangZ Can I close this issue?

**Comment by KaiyangZ** [comment]
Sure, thanks a lot for your help.


 

    On Wednesday, May 25, 2016 12:45 AM, Tom Smith <notifications@github.com> wrote:
 

 @KaiyangZ Can I close this issue?—
