### ISSUE TITLE
Count UMI error

### ISSUE THREAD

**Issue by nicodemus88** [CGATOxford/UMI-tools#174]
Hi to the developers,

I recently tried to use umi-tools but I have an error whenever I tried to use it to count. 

I have a DNA-Seq data with UMI encoded in the tag RX. An example of my BAM file looks like this:

**NS500638:47:H77WVAFXX:4:11506:22315:18530	163	AB513134	97	40	74M	=	715	694	AGACTAAGGCTCTGACGTCTCCCCCCGGAGGGACAGCTCAGCACCGGCTCAGGCTACGCCCGGACGTGTCCCAC	AA66EEEEEEEEEE/E/EEAEEEEEEEE/AAE/EAEE/EAEE//EEEE/E66<A/E/AE/6/////66A<6A/<	MC:Z:76M	PG:Z:MarkDuplicates	RG:Z:sample	MI:Z:5	NM:i:4	MQ:i:60	AS:i:57	XS:i:57	RX:Z:CATTGTGT
NS500638:47:H77WVAFXX:2:11312:13656:8306	163	AB513134	112	40	74M	=	696	660	CGTCTCCCCCCGGAGGGACAGCTCAGCACCGGCTCAGGCTAGGCCCTGACGTGTCCCCCTGAAGACAAATCATA	AAAAAEEEEEEEEEEEEEEEEEEE/EEAEEEEEEE<EEEEEEEEEEEEAAAEEEEAEEEEA6AAAAE<A6<A<E	MC:Z:76M	PG:Z:MarkDuplicates	RG:Z:sample	MI:Z:6	NM:i:1	MQ:i:60	AS:i:69	XS:i:69	RX:Z:TTCGGTGT**

Then I tried to count the number of UMIs using umi_tools with the following command:

umi-tools count --extract-umi-method=tag --umi-tag=RX -I usmg_sort.bam -S test.bam -L log --paired --method adjacency

But I got this error:

**Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==0.5.0', 'console_scripts', 'umi_tools')()
  File "/usr/local/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 50, in main
    module.main(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/umi_tools/count.py", line 67, in main
    U.validateSamOptions(options)
  File "/usr/local/lib/python2.7/site-packages/umi_tools/Utilities.py", line 972, in validateSamOptions
    raise ValueError("for per-gene applications, must supply "
ValueError: for per-gene applications, must supply --per-contig or --gene-tag**

I wonder what is wrong here. My data is not from single cell so I am not using per-gene applications, so I was wondering why I should supply --per-contig or --gene-tag.

Can you help me to identify the problem here?

Thank you very much.

**Comment by TomSmithCGAT** [comment]
Hi @nicodemus88 - Sorry, the error message isn't particularly helpful. The `count` command is currently only set up to count reads per gene.

I'm not exactly sure what you mean by counting UMIs. If you mean counting the total number of UMIs in the whole file after duplicates have been removed, you can run `dedup` and simply count the number of lines in the output BAM. 

If you want to perform some other form of counting, I suggest you run the `group` command. This will group the UMIs on reads with the same alignment coordinates (taking account of soft-alignment) in an error-aware manner. So each group of UMIs is inferred to have originated from one initial molecule. You can then count UMIs per position. The total number of groups will be identical to the number of lines in the BAM from running `dedup` above as suggested. If you swap in the `group` command for `count` above and use the `--group-out=[OUTFILE]` option, it'll output an `OUTFILE` detailing the UMI groups and the genomic coordinate. 

Hopefully one of these approaches will be suitable. If I've missunderstood what you're trying to acheive, feel free to further explain and we'll try and help out

**Comment by nicodemus88** [comment]
Hi @TomSmithCGAT,
Thank you very much for your reply.

Sorry that I didn't specify clearly what I want to do. What I wanted to count is how many reads are coming from any one UMI. I think I got it by doing group and dedup.

However, I have some questions regarding the metrics from the dedup_stats_per_umi. I don't really understand the times_observed and total_counts pre and post dedup. From my data, what I see is that the times_observed is always the same pre and post dedup; but for total_counts, some of the UMI have increased total_counts post dedup.

Could you please explain the meaning of these stats to me? 
Thank you very much.

**Comment by TomSmithCGAT** [comment]
Hi @nicodemus88 - sorry for the very delayed reply.

I'm surprised the "times_observed_pre" and "times_observed_post" values are always the same. These values reflect the number of positions at which the UMI was observed. Hence, the post value should never by higher than the pre value but should frequently be lower. Just to check, if you run the following command do you only get the header returned?
`awk '$6 != $3'  dedup_stats_per_umi.tsv`

The "total_counts_pre" column reflects the number of times the UMI was observed on a read. The "total_counts_post" column is the updated number after the error UMIs have been corrected to the 'true' UMI. They can therefore be changes between the column values which may seem counter-intuitive at first. For example, a UMI can be observed at fewer positions following deduplication but with a higher total number of observations.

By way of an example, if you run the following commands on the `chr19.bam` file in the test directory you can obtain the stats and corresponding UMI groups:
```
umi_tools group -L test.log --out-sam --method=cluster --stdin=chr19.bam --group-out=test.group;
umi_tools dedup -L test.log --out-sam --method=cluster  --output-stats=single_stats -stdin=chr19.bam > /dev/null
```
And then inspect the stats, you'll find that the UMI TACCG was observed at two positions both "pre" and "post", with 4 total reads "pre" and 6 "post"
```
$ awk 'NR==1 || $1=="TACCG"' single_stats_py3_per_umi.tsv
UMI	median_counts_pre	times_observed_pre	total_counts_pre	median_counts_post	times_observed_post	total_counts_post
TACCG	2	2	4	3	2	6
```

When you look for the UMI in the group outfile, the TACCG UMIs fall into two groups, one group at position 4078325, the other group at position 11195965. However, the group at position 407832 also contains 2 reads with the UMI TACAG (see column 6). Since TACCG is deemed to be the "top" UMI for this group, the counts for TACAG are added to the total for TACCG, hence the total of 6 counts. 

```
awk 'NR==1 || $7=="TACCG"' test.group
read_id	contig	position	gene	umi	umi_count	final_umi	final_umi_count	unique_id
SRR2057595.1342749_TACCG	chr19	4078325	NA	TACCG	3	TACCG	5	24
SRR2057595.8450484_TACCG	chr19	4078325	NA	TACCG	3	TACCG	5	24
SRR2057595.11872421_TACCG	chr19	4078325	NA	TACCG	3	TACCG	5	24
SRR2057595.12002442_TACAG	chr19	4078325	NA	TACAG	2	TACCG	5	24
SRR2057595.13110136_TACAG	chr19	4078325	NA	TACAG	2	TACCG	5	24
SRR2057595.8485904_TACCG	chr19	11195965	NA	TACCG	1	TACCG	1	335
```

Just to check, if we look at the stats for TACAG, we can see that it is observed twice "pre" and once "post". Note that the total counts for TACAG only decrease by 1 since it also gains a single count for the one group in which it is retained
```
awk 'NR==1 || $1=="TACAG"' single_stats_py3_per_umi.tsv
UMI	median_counts_pre	times_observed_pre	total_counts_pre	median_counts_post	times_observed_post	total_counts_post
TACAG	39	2	79	78	1	78
```

**Comment by nicodemus88** [comment]
Hi @TomSmithCGAT,
Very sorry for the delayed reply.

Well, if I run the command you supplied, I did not get the header only. This is what I got.

`UMI	median_counts_pre	times_observed_pre	total_counts_pre	median_counts_post	times_observed_post	total_counts_post
AACGTGTA	1	2	2	1	1	1
AAGTGTAT	1	1	1	0	0	0
AATAGTGT	1	4	4	1	3	3
ACCTGTGT	1	9	22	1	8	21
ACGCGTGT	1	1	1	0	0	0
ACGGTGTA	1	2	2	1	1	1
ACTGTTTA	1	1	1	0	0	0
AGATATCG	1	2	2	1	1	1
AGATCTAG	1	1	1	0	0	0
AGTGGTGT	1	1	1	0	0	0
`

Thank you very much for your explanation. I understand the meaning of those stats now. 

Just one question, are there any concerns with the values of 'time_observed_pre' and 'time_observed_post' which does not change after deduplication?

Again, thank you for your patience and kind assistance.

**Comment by TomSmithCGAT** [comment]
@nicodemus88 - Apolgies for my similarly delayed response. 

This all looks OK to me. In all the case above, the UMIs have a value for  "times_observed_post" which is exactly one less than "times_observed_pre", and the "total_counts_post" value is also exactly one less than the "total_counts_pre". This indicates that for each of these UMIs, there was a single occasion where it was observed exactly once at a position and deemed to be an error due to an adjacent UMI. The fact that you only have 10 such events does suggest a very low error rate, but this also depends on how many reads you processed here?

**Comment by TomSmithCGAT** [comment]
Hi @nicodemus88 - Are you OK for me to close this issue?

**Comment by nicodemus88** [comment]
Hi @TomSmithCGAT,
Sorry for the delayed response.
Yes, you can close the issue now. 
Thank you very much for your response and advice here.
