### ISSUE TITLE
group.py does not add UMI tag to both pairs in BAM file

### ISSUE THREAD

**Issue by davidcoffey** [CGATOxford/UMI-tools#179]
When running the following: 
umi_tools group \
-I input.bam \
-S output.bam \
--paired \
--output-bam \
--log=log.file

I expected that both pairs of the paired end bam file would have the addition of the BX and UG tags with the UMI and UMI group respectively.  However, I have come to find out that only one pair is tagged.  Since some of my down stream analyses require tags on both pairs (such as the Picard tool UmiAwareMarkDuplicatesWithMateCigar), it would be great if this change could be made.

Thank you,

David

**Comment by TomSmithCGAT** [comment]
Hi @davidcoffey - The reason for this behaviour is rather esoteric. Essentially, adding the tags to read pairs gets very memory intensive when the reads can have multiple alignments.

Depending on what you're trying to achieve, there are a number of solutions:
- If you want to pass the output of `group` to `UmiAwareMarkDuplicatesWithMateCigar`, you can use the `dedup` command instead
- Alternatively, if you need to perform some steps to the output of group before doing the deduplication and hence 'dedup' is not suitable, it should be possible to write a quick script to parse to bespoke deduplication since the UMI groups have already been identified
- Finally, it should be relatively simple to parse the output and add the tags to the read pairs. I can help you out with this if you absolutely need both reads tagged

**Comment by davidcoffey** [comment]
I was planning on using UmiAwareMarkDuplicatesWithMateCigar to simply calculate my duplication rate.  Can UMI Tools do this instead?

**Comment by TomSmithCGAT** [comment]
Yes. If you pass the option `-L/--log=[FILE]` it will output a log file at the bottom of which you will see lines like so:
```
2017-09-08 17:21:15,574 INFO Reads: Input Reads: 55197
2017-09-08 17:21:15,575 INFO Number of reads out: 726
2017-09-08 17:21:15,575 INFO Total number of positions deduplicated: 540
2017-09-08 17:21:15,575 INFO Mean number of unique UMIs per position: 1.63
2017-09-08 17:21:15,575 INFO Max. number of unique UMIs per position: 23
```
In this instance there were 55197 reads across 540 positions, of which 726 reads were deemed unique, so the duplication rate was 1 - (540/55197) = 0.99021686, or 99%.

**Comment by davidcoffey** [comment]
Thank you, this answers my question and obviates my need to use UmiAwareMarkDuplicatesWithMateCigar.

**Comment by TomSmithCGAT** [comment]
Glad to hear it 😄  Although obviously big fans of `Picard` too!

**Comment by eboyden** [comment]
Sorry to resurrect this thread, but it would be quite preferable if both reads were properly tagged (and additionally, if the 0x400 bitflags were set).  I don't want to use `dedup` because I prefer lossless bams, in part so that downstream analysis tools (e.g. Picard CollectHsMetrics) work properly.  But many of these same tools (Picard, samtools) don't work properly if both reads in a pair aren't similarly tagged and flagged; it's hard for me to think of a use case for the `group` command on paired reads otherwise, since so few downstream tools can properly handle the input.  FWIW fgbio GroupReadsByUmi can do this now, but currently lacks the ability to retain unmapped reads (again, I prefer lossless bams).  Thanks!
