### ISSUE TITLE
extract-method:  regex vs string

### ISSUE THREAD

**Issue by davidcoffey** [CGATOxford/UMI-tools#182]
My library is constructed such that there is a 12 nt UMI followed by a 11 nt universal sequence on read 2 (i.e. 12NATTGGAGTCCT).  Upon reviewing my Fastq files, I see that I have some reads with UMIs which are longer or shorter than 12 nt (e.g. 11NATTGGAGTCCT or 13NATTGGAGTCCT).  My question is, would it be better to use regex as my extract method like this:  bc-pattern='(?P<umi_1>.{12})(?P<discard_1>ATTGGAGTCCT)' such that reads with UMI > or < 12 nt are discarded or should I use the string extract method like this: bc-pattern=NNNNNNNNNNNN so that no reads are removed?

**Comment by TomSmithCGAT** [comment]
Hi @davidcoffey. If you have UMIs which are < or > 12 bp then I'd definitely recommend removing them using the regex you suggest

Out of interest, could you let us know what proportion of reads have a UMI < > 12bp (this information should be in the log file)

**Comment by davidcoffey** [comment]
About 25% of read pairs are discarded when I use the regex approach on one example file.  Below is the output from my extract log file:

Input Reads: 24406688
regex matches read1: 18106126
Reads output: 18106126
regex does not match read1: 6300562

To reduce some of the loss, it would be great if 1) UMIs of varying lengths could be used by the dedup function or 2) some degree of mismatch could be allowed for the universal sequence downstream of my UMI.

**Comment by TomSmithCGAT** [comment]
As yes, I'd forgotten about the reads which will be discarded because of a mismatch in the adapter. Thankfully, the [ `regex`](https://pypi.python.org/pypi/regex/) module supports 'fuzzy' matching. 

For example, to allow one substitution:
`bc-pattern='(?P<umi_1>.{12})(?P<discard_1>ATTGGAGTCCT{s<=1})' `

or one sub. insertion or deletion:
`bc-pattern='(?P<umi_1>.{12})(?P<discard_1>ATTGGAGTCCT{e<=1})' `

**Comment by TomSmithCGAT** [comment]
Hi @davidcoffey - Did the 'fuzzy' matching regexes give you the desired output?

Unfortunately, handling different length UMIs is currently out of the scope of UMI-tools. This is because we currently only handle substitutions since INDELs are usually at least an order of magnitude less frequent than substitutions and harder to handle in our current framework. It's actually a strength of your library that you can identify INDELs using the changing position in the adapter and remove these reads. If you want to estimate the number of UMIs with INDELs which are being discarded, you can try running `extract` with the following patterns and compare the number of reads output. 

```
bc-pattern='(?P<umi_1>.{12})(?P<discard_1>ATTGGAGTCCT{e<=1})'
bc-pattern='(?P<umi_1>.{11,13})(?P<discard_1>ATTGGAGTCCT{e<=1})'
```

I'd be really interested to hear what difference this makes to the number of reads in the output fastq?

**Comment by davidcoffey** [comment]
Hi @TomSmithCGAT, 

I apologize for the delay in my response.  I have been distracted by other projects.

I re-ran the `extract` function using three bc-patterns you recommended in addition to my original which does not support the fuzzy match and below are my results:

1. `bc-pattern='(?P<umi_1>.{12})(?P<discard_1>ATTGGAGTCCT)'`
Input   Reads = 9101205
regex does not   match read1 = 5933219 **(65.2%)**
regex matches   read1 = 3167986

2. `bc-pattern='(?P<umi_1>.{12})(?P<discard_1>ATTGGAGTCCT{e<=1})'`
Input   Reads = 9101205
regex does not   match read1 = 5921142 **(65.1%)**
regex matches   read1 = 3180063

3. `bc-pattern='(?P<umi_1>.{11,13})(?P<discard_1>ATTGGAGTCCT{e<=1})'`
Input   Reads = 9101205
regex does not   match read1 = 5862670 **(64.4%)**
regex matches   read1 = 3238535

4. `bc-pattern='(?P<umi_1>.{12})(?P<discard_1>ATTGGAGTCCT{s<=1})'`
Input   Reads = 9101205
regex does not   match read1 = 5921142 **(65.1%)**
regex matches   read1 = 3180063

As you can see the fuzzy match does improve my matching reads, but not significantly so (I gain only less than 1% more reads).  I'm unsure why this particularly sample had so many discarded reads.
