### ISSUE TITLE
count confusingly uses only the umi as grouping key and ignored the mapping position

### ISSUE THREAD

**Issue by fgp** [CGATOxford/UMI-tools#185]
From the documentation, I expected `count` to use the same grouping algorithm as `dedup` and `group`, but to then simply count the number of distinct (post-grouping) UMIs per gene (identified either by tag or RNAME).

But it seems that`count` will merge similar UMIs within a gene regardless of the mapping position, contrary to how `dedup` and `group` operate. 

I this by design, or is this a a bug? I have to admit that the intended interplay between `--per-gene`,`--per-contig` and `--whole-contig` (which exists only for group and dedup it seems) isn't really clear to me.

**Comment by TomSmithCGAT** [comment]
Hiya @fgp -  This is intended. `count` is currently designed to only handle 3'-Seq data in which reads from the same unique molecule can have different alignment positions since fragmentation occurs after the amplification. This is explained in the [single_cell_tutorial](https://github.com/CGATOxford/UMI-tools/blob/master/doc/Single_cell_tutorial.md#step-5-assigning-reads-to-genes) but I agree the documentation for count is woefully inadequate about this!

If you run `count`, `dedup` or `group` with `--per-gene` you will get this behaviour, e.g ignore position, use just gene assigned. In essence the output of each tool going from group -> dedup -> count is just one step further along the process of counting unique reads per gene. The `--per-contig` and `--gene-tag` options are used to define whether to tag the assigned gene from a gene tag (e.g after `featureCounts -R`) or from the alignment contig (e.g if reads are aligned to a transcriptome).

`--whole-contig` is a completely separate option which forces `umi_tools` to read in every read per contig before defining UMI groups. By default, it processes along the contig and when it has reached 1000bp beyond the last read in a group, it yields the group for deduplication. This is OK for short reads but there may be instances where the user wants to be sure no reads are missed from a group, which is what `--whole-contig` is for. This comes at a significant memory cost however.

**Comment by IanSudbery** [comment]
Just to add...

As @TomSmithCGAT says, all three tools behave the same way if --per-gene or --per-contig are enabled: they ignore the mapping position and only account for the gene/contig the read is aligned to. This is for techinques where fragmenting happens after PCR. However, running group on --per-gene is not encouraged, because all reads on a contig would have to be held in memory to make sure that every read from a gene had been found. This isn't so bad for `dedup` because we only store the best read for each `key`, but it will use more memory than a standard `dedup`. However, we expect most people using `--per-gene` or `--per-contig` to be using `count` as the major use-case is 3' tagging scRNAseq.

`dedup` and `group` will also run in a mode where they will take mapping position into account as well as contig. At the moment count doesn't do this (although I don't quite remember why), but if it did, it would output the count at each position in the genome: the sort of data you might find in a wig or bedgraph file, not each gene in the genome. 

I think we might consider renaming `--whole-contig` to something like `--buffer-whole-contig` or `--disable-read-ahead-buffer`

**Comment by TomSmithCGAT** [comment]
@IanSudbery - I'd be in favour of the re-naming. This has come up a few times so clearly causing some confusion. I like `--buffer-whole-contig`. I think we can still allow use of the `--whole-contig` option (to make this fully backwards compatible) but hide this option from the user.

There's no reason I can think of that we couldn't support `count` in "position" mode if this was really needed.

**Comment by TomSmithCGAT** [comment]
@IanSudbery - I've renamed `--whole-contig` as `--buffer-whole-contig`. The `--whole-contig` option still works this is backwards compatible but the user no longer see this option in the documentation - see #196.

**Comment by TomSmithCGAT** [comment]
@fgp - Can I just confirm that you wanted to use `count` to count reads per gene? I.e the current functionality is sufficient?

**Comment by fgp** [comment]
Well, actually mostly asked because when I was working on that paired-end that's in my pull request, I realized that `count` behaves differently than `group` and `dedup` regarding identical UMIs at different mapping positions. I wanted to confirm that I had read the code correctly, and also to point out that this is (IMHO) highly confusing.

The tool I actually use is `group`, where I post-process the output to contains one line per UMI instead of per read. Later on I reduce that to per-gene UMI counts, but I need that intermediate level of information (read counts for each UMI) as well, so I can't just use `count`.

Having said that, I still feel that it would be better if the "mergability" relation between UMIs wouldn't depend on whether one uses `group`, `count` or `dedup`. In particular because with short UMIs, using only the UMI involves a high risk of collisions, so there's a genuine reason for wanting to include the position.

**Comment by IanSudbery** [comment]
As we said above, there are a fair few techniques that use UMIs where the mapping position is uninformative (because fragmentation happens after amplification), this includes all of the droplet based  and a good number of the non-droplet based single cell RNA seq techniques. 

That said I see no reason why, in principle count shouldn't work on a mapping position basis, outputting something that looking like a bedgraph or wig file. But I think that might be something for the next version rather than a priority - we've not had any demand for it.

**Comment by TomSmithCGAT** [comment]
@fgp -  I agree that it should be made clearer than to `count` is currently hardcoded to run in `--per-gene` mode, in which case it handles UMIs in the exact same way as `dedup` and `group` run in `--per-gene` mode. The top of the documentation for `count` does make clear that it only handles counts per reads right now

```
count.py - Count reads per gene from BAM using UMIs
[...]
The purpose of this command is to count the number of reads per gene based
on the mapping co-ordinate and the UMI attached to the read.
```

There is a genuine problem with collisions in short UMIs for gene counting. However, I think it's reasonable to say the problem is one of experimental design. If a user wants to come up with their own solution, they can of course use the `group` command and implement their own bespoke counting based on the UMI groups detected.

@IanSudbery - Agree we should leave this until the next version. I've tagged accordingly

**Comment by TomSmithCGAT** [comment]
@IanSudbery - An old issue that has been in the "consideration" pile. Since this issue, we've clarified in the docs that `count` is hardcoded to work on a per-gene basis and that it is designed explicitly for scRNA-Seq data where fragmentation occurs post amplification in the library prep. 

Personally, I don't see the need to implement a mapping-position version of count. If a user requires this they can simply run `dedup` and perform simple processing of the deduplicated BAM to count reads per gene. I propose we close this issue for now.
