### ISSUE TITLE
UMI Tools Dedup on Paired End reads

### ISSUE THREAD

**Issue by Vaishn17** [CGATOxford/UMI-tools#186]
When ```--paired``` option is given on ```umi_tools dedup```, it seem to inherently remove the singletons. Is there way I can keep them in the resulting bam file?

**Comment by TomSmithCGAT** [comment]
HI @Vaishn17 - This is because for paired reads we use the mapping position of the first read, and the length of the fragment to identify potential duplicate reads. Where the reads aren't paired, it's not possible to determine which read group to assign the read as we don't have both bits of information.

If you really want to keep the singleton reads, you can run `group` with the `--output-unmapped` and `--output-bam` options. This will output the reads at the earlier UMI grouping stage with BAM tags specifying the UMI group for each read. The output BAM will also contain all unmapped reads and should also contain singletons (I haven't checked this). Note that the singletons will not be assigned a UMI group. You will then need to parse the output BAM to remove duplicate reads and retain singletons as required.

**Comment by TomSmithCGAT** [comment]
@Vaishn17 - Did you manage to parse the BAM output from `group` for your intended purposes?

**Comment by Vaishn17** [comment]
@TomSmithCGAT I isolated the singleton reads and and used UMI information from them outside of UMI tools.
