### ISSUE TITLE
Error when installing with conda

### ISSUE THREAD

**Issue by LehmannN** [CGATOxford/UMI-tools#205]
Hello, 

I just wanted to point out that, sorry if you are already aware of this issue, when installing UMI-tools with the command `conda install -c https://conda.anaconda.org/toms umi_tools` (in the README file), it returns an error message, such as : 

```
PackageNotFoundError: Packages missing in current channels:
            
  - umi_tools -> pysam >=0.8.4
  - umi_tools -> bcftools ==1.3
  - umi_tools -> htslib >=1.3
  - umi_tools -> samtools >=1.3
```
However, on the conda website, one can find the command`conda install -c bioconda -c toms umi_tools` (or `conda install -c bioconda -c https://conda.anaconda.org/toms umi_tools`) which works, but install an older version of UMI-tools, with only 3 tools (extract, group and dedup). 

Do you think there will be an updated version of UMI-tools in conda (with the 6 tools) rather soon ? 

Thank you very much, 

Nathalie

**Comment by TomSmithCGAT** [comment]
Hi @NathalieLehmann,

The error message suggests to be that you don't have the necessary conda channels to install `pysam` etc. The easiest route would be to make the bioconda channel available. Could you try running the commands under "Set up channels" [ here](https://bioconda.github.io/) then re-run `conda install -c https://conda.anaconda.org/toms umi_tools`.

Also, what OS and python version are you using?

**Comment by IanSudbery** [comment]
@NathalieLehmann 

You say `conda install -c bioconda -c toms umi_tools` gives you an old version of umi_tools.  What does `conda install -c toms -c bioconda umi_tools` do?

@TomSmithCGAT 
I asked the question above because we need to amend the documentation to point out that bioconda is necessary. I don't now if its best just to tell people to add bioconda to their channels or to add it temporarily if the above works. They ask people to add conda-forge on the bioconda page, which makes me nervous. I don't know what its like now, but conda-forge used to contain bleeding-edge, non-stable versions of things, and I feel like it might not be a good idea to advise people to add it permanently unless they know what they are doing (and I don't think any of our dependencies require it). Same goes for the r channel - people are not going to want a conda r override their carefully set up system r if they can avoid it.

**Comment by NathalieLehmann** [comment]
@IanSudbery 
Here is what I get when typing `umi_tools` after an installation with conda : 
```
umi_tools.py - Tools for UMI analyses
===============================================

:Author: Tom Smith & Ian Sudbury, CGAT
:Release: $Id$
:Date: |today|
:Tags: Genomics UMI

There are 3 tools:
  - extract
  - group
  - dedup
```
You can see that 3 tools are missing :` whitelist, count` and `count_tab`. So I assumed it was due to an older version of UMI-tools. When doing the installation with `pip `or from the git repository, you get all the 6 tools. 

@TomSmithCGAT 
Thank you, making the bioconda channel available fixed the problem. I have tried to installed it with the conda command with Linux (python 3.6) and Mac (python 2.7), both returning the same result.
