### ISSUE TITLE
gettag function splits multiple UMIs

### ISSUE THREAD

**Issue by jdc8890** [CGATOxford/UMI-tools#217]
Hello,

Our experimental setup contains multiple UMIs per read.  These are stored within the RX tag and are concatenated together by dashes (e.g. UMI1-UMI2-UMI3).  It looks like the gettag function splits the UMI by dashes and only considers the first portion in order to be compatible with GEM tags in the 10X pipeline.  As a result, only the first UMI is considered when extracting and grouping the reads.  Can this function be modified in some way to support multiple UMIs?

Thank you.

**Comment by TomSmithCGAT** [comment]
Hi jdc8890 - This sounds like a simple issue to solve. I'll aim to get something sorted soon early next week

**Comment by jdc8890** [comment]
Great, thanks so much!  Much appreciated.

**Comment by TomSmithCGAT** [comment]
@jdc8890 - How were the UMI tags added to the BAM and is there any reason why the UMIs are separated in the RX tag? If not, the easiest thing to do is to store the UMIs as a single concatenated UMI in the RX tag.

**Comment by TomSmithCGAT** [comment]
@jdc8890 - I've added an option, `--umi-tag-delimiter`. If used, this will tell `umi_tools` the UMI contains multiple sequences separated by this delimter. The UMIs are no longer split by "-" by default since the 10X pipeline only adds the suffix to the cell barcodes. Hence, if you add the following option it should concatenate your UMIs:
`--umi-tag-delimiter=-`

Before I merge these changes into the master branch, would you be able to test whether this works by installing directly from the [{TS}-Add_UMI_tag_sep_options](https://github.com/CGATOxford/UMI-tools) branch. I can give you instructions for how to do this if you need them.

**Comment by jdc8890** [comment]
Thanks so much, @TomSmithCGAT.  Happy to test the changes.  Can you point me to instructions for how to install directly from the branch?

**Comment by TomSmithCGAT** [comment]
You can install the branch version using:
`git clone git@github.com:CGATOxford/UMI-tools.git` (if you haven't already cloned the repository)
`cd UMI-tools`
`git fetch` (fetch the branches)
`git checkout  {TS}-Add_UMI_tag_sep_options` (switch to the branch)
`python setup.py develop` (install umi_tools)

Alternatively, I believe you can install directly using `pip` though I haven't done this myself. There are some instructions [here](https://coderwall.com/p/-wbo5q/pip-install-a-specific-github-repo-tag-or-branch)

**Comment by TomSmithCGAT** [comment]
`umi_tools >= v0.5.2` now includes these additional options. Feel free to reopen this issue if you have any issues with these options
