### ISSUE TITLE
This tool is based on what rules to determine the duplicate？

### ISSUE THREAD

**Issue by elainebblythe** [CGATOxford/UMI-tools#258]
Hi，my aim is to find snp,and I select use GATK's pipline to do it. As far as I know the Picard'MarkDuplicates define the same sequence as duplicate,It does not make use of the UMI sequences.So,I want to know 
1）this tool is based on what rules to determine the duplicate？
2）Can this output be used for downstream GATK analysis?

**Comment by elainebblythe** [comment]
@TomSmithCGAT 
thanks for your reply.I have another question.Is this tool suitable for all types of data? e.g.WES or WGS

**Comment by elainebblythe** [comment]
@TomSmithCGAT 
Hi,I read this paper,but But one thing I don't understand.
According to this paper,dedup takes an alignment BAM file, identifies reads with the same genomic coordinates and same UMI sequence as potential PCR duplicates.

(my data is pair-end sequence,the UMI is 8bp)
the UMI of read1 and read2 is not separate,if there are two reads,after alignment,they share the same position,and these head is ：
BR8K2:1:1101:10000:13913_GATTACCGCTTAGGAC
BR8K2:1:1101:10000:15916_CTTAGGACGATTACCG

The order of the two UMIs is just the opposite,Theoretically, these two sequences originate from the same double-stranded molecule,I want to know in the umi_tools,will this type of sequence be considered  as duplicate? the GATTACCGCTTAGGAC is not similar to CTTAGGACGATTACCG ,but it should be the duplicate

**Comment by TomSmithCGAT** [comment]
HI @elainebblythe. As far as I'm aware, the example you give above shouldn't happen since the adapters which define the read1 and read2 also contain the UMIs. Is the example you give a real example, or a theoretical one? If it's real, is it possible it's a very rare coincidence or do you have multiple examples like this. Finally, what library preparation kit/method did you use?

**Comment by elainebblythe** [comment]
@TomSmithCGAT 
Maybe I didn’t express clearly，Duplex sequence is actually a kind of duplicate，Can this tool remove the duplex?

**Comment by TomSmithCGAT** [comment]
Hi @elainebblythe - I confess I hadn't come across Duplex sequencing before. I can see how the above example could originate now.

Unfortunately, UMI-tools is not explicitly designed to handle duplex sequencing and the above examples would not be considered duplicates. From a quick skim of the wikipedia page on duplex sequencing I gather that the ultimate aim is to identify mutations. In this case, you want to identify the groups of duplicate reads in order to derive a consensus sequencing. You could achieve this using `umi_tools group` to first identify the groups of reads based on the concatenated UMIs in the direction they are sequenced, then parse this output to identify the pairs of groups where they share the same UMIs but in opposite orientation. From these pairs of groups, you could then derive the consensus sequence. This will obviously require some additional bespoke code but the advantage of using `umi_tools group` to identify the initial groups is that this will be done in an error-aware manner.

**Comment by elainebblythe** [comment]
@TomSmithCGAT 
OK,I got it. thank you very much

**Comment by Tato14** [comment]
Hi @elainebblythe,

Struggling with exactly the same pipeline. Did you finally merge the two pipelines?

Thanks!

**Comment by elainebblythe** [comment]
No, I wrote a script that filtered the duplicate, based on the two UMIs and the alignment location.



elaineylq@163.com
 
发件人： Tato14
发送时间： 2018-09-12 16:04
收件人： CGATOxford/UMI-tools
抄送： elainebblythe; Mention
主题： Re: [CGATOxford/UMI-tools] This tool is based on what rules to determine the duplicate？ (#258)
Hi @elainebblythe,
Struggling with exactly the same pipeline. Did you finally merge the two pipelines?
Thanks!
