### ISSUE TITLE
indels close to 5' end

### ISSUE THREAD

**Issue by retrogenomics** [CGATOxford/UMI-tools#260]
Hi,
Using Ion Torrent sequencing which is prone to indels, I often get something like this after deduplication:
![capture d ecran 2018-06-29 a 13 17 50](https://user-images.githubusercontent.com/7796846/42089766-f9441508-7b9e-11e8-80aa-f989eecaf84c.png)

It is obvious that the a G insertion is responsible for the 5' soft clipped part of the read and ultimately to keep this read upon deduplication. I was wondering if there would be an easy work-around for this. 

Thanks in advance for your help

**Comment by IanSudbery** [comment]
I can't currently think of any good way to get around this. The best thing you could do would be the alter the parameters to your mapper to reduce the penalty for an insertion so that such reads are mapped with an insertion rather than a softclip. Alternatively you could filter out any reads with softclipping.

**Comment by retrogenomics** [comment]
Yes, you're right: filtering reads starting with a softclip should make the job. Thank you for your input.
