### ISSUE TITLE
dedup not recognizinding UMI tag

### ISSUE THREAD

**Issue by eldadshulman** [CGATOxford/UMI-tools#262]
Hi,

I am trying to use dedup on a bam file produced by cell ranger.

However, when using --umi-tag=UB, I get the following error: 
KeyError: "tag 'UB' not present".
When I use --umi-tag=UR, I do not get this error.
Is it possible to use UB as the umi tag?

Eldad

**Comment by IanSudbery** [comment]
The problem here is that cell ranger does not add a UB tag to every read, so UMI-Tools doesn't know what to do with reads that don't have a UB tag.  These reads don't have a CB tag either, so I'm guessing they are reads that didn't pass whitelist filtering. 

CR barcodes are barcodes corrected using cellrangers own UMI correction algorithm. We would recommend apply first the cellranger algorithm and then ours, as we make a number of assumptions that wouldn't be true after deduplication with the cellranger pipeline.

**Comment by eldadshulman** [comment]
Thank you very much.

Just to make sure I understand your recommendation. You suggest to first filter the reads that do not have a UB/CB tag out of the bam file, and then run dedup with  --umi-tag=UB , --cell-tag=CB?

**Comment by IanSudbery** [comment]
That will "work" in that no errors will be thrown, but you won't be very good output from it.

The sequence in UB is the cellranger corrected UMI sequence. It is effectively their version of what we do and you do not want to perform their correction followed by ours, ours wouldn't work properly. 

If you wish to use our method for barcode correction I recommend you use `--umi-tag=UR --cell-tag=CR`. 

If you just want to use UMI-Tools to obtain a deduplicated BAM, but using cellranger's algorithms rather than ours, then filter the BAM to remove reads that don't have a UB/CB tag and run dedup/count with `--umi-tag=UB --cell-tag=CB --method=unique`

**Comment by eldadshulman** [comment]
Thanks!
