### ISSUE TITLE
predefinition of subset-reads in whitelist.py

### ISSUE THREAD

**Issue by profhw** [CGATOxford/UMI-tools#263]
Is this default setting for any reason?
https://github.com/CGATOxford/UMI-tools/blob/fa9c2247f2b4cb159b270ffaddb9f2f15eed354f/umi_tools/whitelist.py#L184

I just realized that many whitelist log files contain a "100000001 reads matched the barcode pattern" line even though the number of the input reads varies significantly and I did not use the --subset-reads option.
Since I got an expected result by changing Line 184 of whitelist.py to "subset_reads=None," I guess that such a change may be more appropriate.

If there is any reason for the default setting, I hope it will be noted in the documentation clearly.

**Comment by TomSmithCGAT** [comment]
Hi @profhw - The `--subset_reads` option defaults to 100M reads because in all cases tested to date this is sufficient to determine the distribution of read/UMI counts per cell barcode and parsing additional reads is therefore of no benefit. The documentation for `whitelist` (`--help`) currently says the following, though I agree it should also state the default value is 100M:

```
   --subset-reads=SUBSET_READS
                        Use the first N reads to automatically identify the
                        true cell barcodes. If N is greater than the number of
                        reads, all reads will be used
```

**Comment by TomSmithCGAT** [comment]
Yes, set to 0 or >#reads to parse all reads. I'll add this to the documentation of the option too. Thanks
