### ISSUE TITLE
Deduplication with UMI-tools in highly duplicated samples

### ISSUE THREAD

**Issue by gsaenzdepip** [CGATOxford/UMI-tools#265]
Hello, I am using UMI-tools for deduplicating some RNA-seq samples. I have high duplication levels due to the protocol used for library generation (MARS-seq). We use this protocol to capture mRNA and study gene expression in samples with low RNA input. However, after using UMI-tools the duplication levels are still higher than 50% in most of the samples. Is this normal or should I change some UMI-tools parametres? I use the output BAM file (from STAR aligner) as input for **UMI-tools dedup**. Should I use first other function such as **UMI-tools group**?

Many thanks, Goren

**P.D:** In this image you can see that, for example, sample "CCI-121" has 96% duplicates before using UMI-tools and 76% after deduplication. I measured duplication levels using Picard.

https://ibb.co/eoAmDd

**Script for UMI-tools:**
umi_tools dedup -I /input.bam --output-stats=/output/directory/stats -S /output.bam  --buffer-whole-contig

**Script for Picard:**
picard MarkDuplicates REFERENCE_SEQUENCE=/reference/genome INPUT=/input.bam OUTPUT=output.txt REMOVE_SEQUENCING_DUPLICATES=FALSE ASSUME_SORTED=TRUE METRICS_FILE=output.txt CREATE_INDEX=TRUE

**Comment by TomSmithCGAT** [comment]
Hi @gsaenzdepip. Your `picard MarkDuplicates` command ignores UMIs. Thus, two reads with the same alignment coordinates with be considered duplicates even if they have different UMIs. The duplication rates you have obtained are therefore over-estimates. There's actually no need to quantify duplication levels post `umi_tools dedup` since this tool is explicitly designed to remove all duplicate reads. If you want to determine the duplication rate according to `umi_tools`, you can use

`1 - (# reads post-UMI-tools / # reads pre)`

The right hand side of the above is what you have in parentheses in the No reads after deduplication column. For example, your CC-121 sample has duplication rate of (1-(1309295/9547864)) = 0.86 = 86%. 

Your results actually look positive to me. Had you used a library preparation without UMIs, you would have an apparent duplication rate of 92-96% per sample, thus only 4-8% of your reads would be retained for downstream analyses. Since you used UMIs, it's possible to more accurately estimate the duplication rates (86-91%) and 9-14% of your reads can be retained.

P.s If you want to compare the UMI-tools duplication rate estimate with `picard` and your BAM contains the UMI in a read tag, you can provide the `BARCODE_TAG=[tag]` option to get `picard`'s estimate, taking into account UMIs. Note, it's not possible to accurately estimate the duplicate rate in the deduplicated BAM with any tool since we have removed reads which will invalidate the assumptions underlying any method to estimate duplication rate.

**Comment by gsaenzdepip** [comment]
Perfect. Thank you Tom!
