### ISSUE TITLE
Levenshtein distance for "--error-correct-threshold"

### ISSUE THREAD

**Issue by mbahin** [CGATOxford/UMI-tools#291]
Hi!

Is there a reason for the whitelist option "--error-correct-threshold" to use the Hamming distance instead of the Levenshtein distance?
Levenshtein distance is better for DNA sequence comparison no? (to allow indels)

Cheers,
Mathieu

**Comment by IanSudbery** [comment]
Hi Mathieu,

Its mostly a case of computational complexity. Calculating the Hamming distance is O(n), but the theoretical minimum for computing the Levenshtein distance is O(n^2) and most actual implementations are less efficient than this: effectively you have to do a full local alignment of the two sequences. Since we compute all pairwise distances between UMIs in a particular group, this is very computationally expensive.

In the paper we examined the effect of indels in the UMI and found them to be a tiny problem compared to substitution errors. Further we found that if we did a simple minded collapsing of UMIs with single base deletions or insertions, you would end up removing far more genuinely independent UMIs than things that actually arose from indel errors. See the analysis here: https://github.com/CGATOxford/UMI-tools_pipelines/blob/master/notebooks/Examine_indels.ipynb

**Comment by mbahin** [comment]
Thanks Ian for your answer.
I must admit that I was a bit sceptical at first but I checked my data and actually I discovered that you were right, most of the errors are substitutions. :)
