### ISSUE TITLE
count: error: no such option: --assigned-tag

### ISSUE THREAD

**Issue by gangcai** [CGATOxford/UMI-tools#293]
Hi,
      I installed umi_tool through pip, and it seems that it doesn't have --assigned-tag option suggested in the tutorial.

Thanks,
Gangcai

**Comment by gangcai** [comment]
```bash
umi_tools count --per-gene --gene-tag=XT --assigned-tag=XS --per-cell -I "$srx_id"_assigned_sorted.bam -S "$srx_id"_counts.tsv.gz
```

**Comment by TomSmithCGAT** [comment]
Apologies @gangcai, this option is now called `--assigned-status-tag` to make it clearer what the option is for. I'll update the documentation now. Thanks for raising this!

**Comment by gangcai** [comment]
Hi Tom,
 Thanks for your reply. I changed as you suggested, however it seems that the same error occurs.
"count: error: no such option: --assigned-status-tag".

**Comment by gangcai** [comment]
By the way, should it be "--umi-tag" ? I changed the command to : 
```bash
umi_tools count --per-gene --gene-tag=XT --umi-tag=XS --per-cell -I "$srx_id"_assigned_sorted.bam -S "$srx_id"_counts.tsv.gz
```

**Comment by rebeccagj** [comment]
Hi @TomSmithCGAT, I am still having this same error as well, regardless of whether I use `--assigned-tag` or `--assigned-status-tag`

**Comment by TomSmithCGAT** [comment]
Sorry @gangcai, I missed your message. @rebeccagj & @gangcai - could you confirm which version of `umi_tools` you have installed. Thanks

**Comment by rebeccagj** [comment]
```
$ pip install --upgrade --force-reinstall umi_tools
$ umi_tools --version
UMI-tools version: 0.5.4
```

Also when I do `umi_tools count --help`, I see no `--assigned-tag` or `--assigned-status-tag` options in the man page that comes up (attached is the output I get in case that is helpful too)
[umi_count.log](https://github.com/CGATOxford/UMI-tools/files/2586755/umi_count.log)

**Comment by TomSmithCGAT** [comment]
Hi both, I'd missed that this option was not included in v0.5.4. The original commit was made in January (https://github.com/CGATOxford/UMI-tools/commit/52bb5daff19c300cea1d098eb0d51d0c172ae498) which is why I'd assumed it was included but it wasn't merged into master until 26th September (https://github.com/CGATOxford/UMI-tools/pull/282)  and 0.5.4 was released on 16th July.

It looks like we've actually got quite a difference now between the GitHub version and the most recent `pip`/`conda` versions so we'll issue 0.5.5 shortly. In the meantime, if you want to use the `--assigned-status-tag` option, you can install from github

**Comment by TomSmithCGAT** [comment]
Version 0.5.5 has been released on [pypi](https://pypi.org/project/umi_tools/). I'll make a pull request for the version bump on bioconda when the tests have run.

Could you please update `umi_tools` and confirm this has resolved the issue. Thanks!

**Comment by TomSmithCGAT** [comment]
v0.5.5 is now availabe on `bioconda` too. I'm going to assume this has been resolved now. Please re-open the issue if not.
