### ISSUE TITLE
No UMI

### ISSUE THREAD

**Issue by latacca** [CGATOxford/UMI-tools#298]
How do I make a whitelist without UMI? The paper says the reads have a barcode but do not have UMI.

If I have 300 different SRA files from the same project. And each of them is a different cell, shouldnt I expect that each SRA is gonna have just one barcode, since barcodes is for determining the cell? Does it mean I am going to need a whitelist for each SRA file?

**Comment by TomSmithCGAT** [comment]
Hi @latacca. If I understand your input correctly, you don't need to use UMI-tools at all.

If you have 300 different SRA files, each containing one cell, you can perform the quantification with each SRA separately and then merge post-quantification. I expect there are also tools to merge the inputs in a way which retains the sample information so you can perform a single quantification run but I don't think UMI-tools will help you here.

**Comment by dawe** [comment]
I'm actually struggling with a similar problem: we are running scATAC-seq with 10x platform: the cell information is on R2 and it is 16bp with cellular barcode only. Quantification of CB could be used to decide the amount of cells (with the very same approach used in scRNA-seq) but UMI are not needed here (in fact, duplicated reads are intended in the "traditional way", that is paired-end reads mapping in the same position). Indeed I can create a whitelist from sequences in R2 (simply using bash tools `zcat file_R2.fastq.gz  | paste  - - - -| cut  -f 2 | sort | uniq -c | sort -k1,1rn`), but that doesn't consider edit distances.

**Comment by TomSmithCGAT** [comment]
Hi @dawe  - If you want to run `whitelist` without considering UMIs, you just need to add `--method=read` (so that the counts per cell barcode are the number of reads) and then provide a barcode pattern which does not include any UMI bases, e.g something like `--extract-method=string --bc-pattern=CCCCCCCCCCCCCCCC` if the read contains just a 16 nucleotide cell barcode. 

The full documentation for the options is here: https://umi-tools.readthedocs.io/en/ts--addfaq/reference/whitelist.html

**Comment by dawe** [comment]
I’m trying this tomorrow, then. I may open another issue as there are 3 reads (two pairs and one for CB), it seems options let me operate on two fastqs at the time (not a big issue, I can always process CB+R1 and CB+R2 separately, assuming umi_tools always outputs reads in the same order)
