### ISSUE TITLE
UMI directional adjacency count comparison

### ISSUE THREAD

**Issue by tylo42** [CGATOxford/UMI-tools#32]
Unless I'm misunderstanding what is going on in `_get_adj_list_directional_adjacency` (https://github.com/CGATOxford/UMI-tools/blob/master/umi_tools/dedup.py#L308), it appears that the comment and the code do not match. The comments claim that the UMI counts are compared with a greater than comparison, but the code compares them with a greater than or equal to symbol. I noticed this because at locations where each UMI is unique some reads were still getting removed. (For example 1 >= (1\*2)-1 is true, but 1 > (1\*2)-1 is false). This was unexpected based on my understanding of the blog post about the tool (https://cgatoxford.wordpress.com/2015/08/14/unique-molecular-identifiers-the-problem-the-solution-and-the-proof/) and the command help output.

```
    def _get_adj_list_directional_adjacency(self, umis, counts, threshold):
        ''' identify all umis within the hamming distance threshold
        and where the counts of the first umi is > (2 * second umi counts)-1'''

        return {umi: [umi2 for umi2 in umis if
                      edit_distance(umi.encode('utf-8'),
                                    umi2.encode('utf-8')) == 1 and
                      counts[umi] >= (counts[umi2]*2)-1] for umi in umis}
```

**Comment by TomSmithCGAT** [comment]
You're correct that the code does not match up with the documentation - I'll update this. Thanks for pointing this out.

Since the blog post, we've switched to using Na >= (2* Nb) - 1, where Na = Node A and Nb = Node b, as described in the  [pre-print](http://biorxiv.org/content/early/2016/05/10/051755.full.pdf+html). This threshold was found to slightly improve the edit-distance relate to the null distribution compared to the previous threshold of Na > 2* Nb described in the blog post. In essence, this slight change in the heuristic threshold allows nodes to still be joined in regions of low read depth, as in your example with single count UMIs. Of course, if you use the adjacency or cluster methods, the counts will not be taken into consideration whatsoever. 

It's worth noting that in practice, we see very little difference between adjacency and directional adjacency methods with real data.

**Comment by tylo42** [comment]
Thank you so much for you quick and detailed response!
