### ISSUE TITLE
UMI in read 2

### ISSUE THREAD

**Issue by juliaesser** [CGATOxford/UMI-tools#331]
Hi,
Im new into bioinformatics and have a question concerning the UMI extraction.
Im using paired end extraction and my UMI is located on read 2, how can I specify that using the UMI extraction tool? I already tried this command line in terminal (--3prime)  to sepecify that it is on the 3' end of the read but how exactly can I specify that it is on read 2 instead of read 1. Maybe by using --bc-pattern2 instead of only --bc-pattern?

umi_tools extract -I 13_S13_L001_R1_001.fastq.gz --bc-pattern=NNNNNNNNN  
  --read2-in=13_S13_L001_R2_001.fastq.gz --stdout=processed.1.fastq.gz 
  --read2-out=processed.2.fastq.gz –-3prime

**Comment by TomSmithCGAT** [comment]
Off the top of my head I can't remember if `umi_tools extract` will error with only `--bc-pattern2` but if it does, you can simply swap the order of the input files, e.g:

```
umi_tools extract -I  13_S13_L001_R2_001.fastq.gz--bc-pattern=NNNNNNNNN
--read2-in=13_S13_L001_R1_001.fastq.gz --stdout=processed.2.fastq.gz
--read2-out=processed.1.fastq.gz –-3prime
```

**Comment by juliaesser** [comment]
Thank you very much @TomSmithCGAT 
It worked better with your advice.

But:

I looked in to my fastq Files again and noticed, that the position of my UMIs varyied a lot. Mostly it is somewhere in the middle/ end part of Read 1 but sometimes also in the beginning of read 2. With which command could I extract the UMIs then?

**Comment by TomSmithCGAT** [comment]
When you say the UMI is in different locations within the read, how are you working out where it is? Is there some adapter sequence etc which you are using to identify the position of the UMI within the read? If so, it should be possible to use match the read sequence to a regex which will allow the precise position of the UMI within the read to vary, so long as the read sequence matches the regex. For example, when working with indrop scRNAseq, the following options can be used to specify that the read should contain in order:

- 8-12 nt cell barcode: `(?P<cell_1>.{8,12})`
- GAGTGATTGCTTGTGACGCCTT (allowing two errors): `(?P<discard_2>GAGTGATTGCTTGTGACGCCTT{s<=2})`
- another 8 nt of cell barcode: `(?P<cell_3>.{8})`
- 6 nt UMI: `(?P<umi_1>.{6})`
- 3 Ts: `T{3}.`

```
--extract-method=regex
--bc-pattern="(?P<cell_1>.{8,12})(?P<discard_2>GAGTGATTGCTTGTGACGCCTT{s<=2})(?P<cell_3>.{8})(?P<umi_1>.{6})T{3}.*"
```

Formatting the regexes can be a bit tricky. Especially since we use the non-standard `regex` module, rather than `re`, in order to allow "fuzzy" matching. There's a section in the documentation dealing with regexes: https://umi-tools.readthedocs.io/en/latest/regex.html#regex-regular-expression-mode

**Comment by TomSmithCGAT** [comment]
I'm closing this issue down due to inactivity.
