### ISSUE TITLE
No UMIs option not working when method is "reads"

### ISSUE THREAD

**Issue by dawe** [CGATOxford/UMI-tools#332]
Following up on issue #298 , I've tried to extract the whitelist for scATAC-seq data. As suggested I've used the `reads` method but it complains about missing UMI specification

```
umi_tools whitelist --method=reads --extract-method=string --bc-pattern=CCCCCCCCCCCCCCCC -I full_10x_R2.fastq.gz -S full_10x_whitelist.tsv
```

I get this error:

```
Traceback (most recent call last):
  File "/home/dcittaro/miniconda3/bin/umi_tools", line 10, in <module>
    sys.exit(main())
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/umi_tools/umi_tools.py", line 61, in main
    module.main(sys.argv)
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/umi_tools/whitelist.py", line 338, in main
    extract_cell, extract_umi = U.validateExtractOptions(options)
  File "/home/dcittaro/miniconda3/lib/python3.6/site-packages/umi_tools/Utilities.py", line 1131, in validateExtractOptions
    U.error("barcode pattern(s) do not include any umi bases "
NameError: name 'U' is not defined
```

which sounds like a "double bug": first it tries to raise the error that UMI are not included in the pattern, second, `U` is not defined

**Comment by TomSmithCGAT** [comment]
Should have checked this myself before suggesting. I'll take a proper look early next week

**Comment by dawe** [comment]
This patch seems to work:

```
diff --git a/umi_tools/Utilities.py b/umi_tools/Utilities.py
index a4f904f..baeea2d 100644
--- a/umi_tools/Utilities.py
+++ b/umi_tools/Utilities.py
@@ -1127,7 +1127,7 @@ def validateExtractOptions(options):
                 extract_umi = True
 
     if not extract_umi:
-        if options.extract_method == "string":
+        if options.extract_method == "string" and options.method != 'reads':
             U.error("barcode pattern(s) do not include any umi bases "
                     "(marked with 'Ns') %s, %s" % (
                         options.pattern, options.pattern2))
```

**Comment by dawe** [comment]
FYI, the workaround works with “whitelist” but not with “extract”, as method “reads” is not an option for that module

**Comment by TomSmithCGAT** [comment]
On reflection, I think there's a bit of a question here whether this functionality is going beyond what should be possible in UMI-tools. The `whitelist` and `extract` tools are pretty much in place to help enable users to get the fastq file in the expected format prior to alignment. The real "meat" of UMI-tools are the `dedup` etc commands. Indeed, at the time of publication, there was no `whitelist` command since there was no need for it to analyse the data in the publication and one could still use any alternative method to identify the cell barcodes.

In your case, I wonder if you might be better off using `sircel` (https://github.com/pachterlab/sircel ;https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2612-0) since this is designed explicitly for this task

**Comment by dawe** [comment]
I see more and more people using UMItools in single cell data. As new approaches and technologies are coming, I foresee people familiar with UMItools asking for new functions so they don’t need to include another tool in their pipelines.
As for my analysis, I had to include barcodes as RG tags to my BAM file, I had to write a small (and quite inefficient) script to do it starting from the whitelist and the fastq with barcodes, so I’m not trying `sircel` in the near future, but thanks for the advice

**Comment by TomSmithCGAT** [comment]
I'm closing this issue down due to inactivity.
