### ISSUE TITLE
deduplication without mapping 

### ISSUE THREAD

**Issue by achevuw** [CGATOxford/UMI-tools#334]
Thanks in advance for the help. 

I have a slightly unusual dataset generated with UMIs.  Was able to extract UMIs using umi_tools extract just fine.  However I don't have a reference to map the reads to.  It's a deep sequencing experiment not a fragment library.  Is it possible to deduplicate without the mapping step, maybe by creating an unmapped bam file?  

Suggestions for converting my extracted .fastq to an unmapped bam file?  I've been trying with picard tools FastqtoSam but am getting an error when trying to run umi_tools dedup:

Workflow now:  

>umi_tools extract --stdin=myfile.fastq.gz --bc pattern=NNNNNNNNNNNNNNNNNNNN --log=processed.log --stdout myfile_processed.fastq.gz

>java -jar picard.jar FastqToSam F1=myfile_processed.fastq O=myfile_unaligned_reads.bam SM=sample001 RG=rg0013

>umi_tools dedup --stdin=myfile_unaligned_reads.bam --log bam_dedup.log > myfile_dedup.bam

File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 985, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False

**Comment by TomSmithCGAT** [comment]
I'm not clear what you mean by a deep sequencing experiment. Are you referring to sequencing a single genomic region to a high depth in order to detect low frequency clonal types? If so, you may be able to perform the read de duplication using the UMI-tools network methods directly - see https://umi-tools.readthedocs.io/en/latest/API.htm

UMI-tools is explicitly designed to work from aligned reads so I don't expect there will any work around for the command line tools which will be suitable.

**Comment by TomSmithCGAT** [comment]
For anyone who comes to this issue wanting to deduplicate without alignment, this paper may be of interest: https://academic.oup.com/bioinformatics/article-abstract/35/11/1829/5142725?redirectedFrom=fulltext

I have no experience of using `calib` and it appears to require some user-defined parameterisation for optimal performance but thought this was worth posting before I close this issue at least
