### ISSUE TITLE
--multimapping-detection-method

### ISSUE THREAD

**Issue by casimonet** [CGATOxford/UMI-tools#34]
Hi,
I have a short question related to the --multimapping-detection-method

the help specifies that "Setting this option to NH, X0 or XT will use these tags when selecting the best read amongst reads with the same position and umi"
Does it means that if several reads map at the same position/same strand/same umi, a read with a tag stating it is a secondary alignment will be less preferably selected?

I am specifically interested in the expression of Transposable Elements .
After this dedup step I will input the resulting bam file in TEtranscript for a subsequent analysis. This algorithm uses the information of the distribution of the multimapped reads to estimate the most likely alignment of each repeat, so I must make sure that the dedup from umi-tools is not going to bias my data by potentially arbitrarily eliminating reads because there are secondary alignment.

Thank you,
Camille

**Comment by TomSmithCGAT** [comment]
Hi Camile,

You're correct that a read which is multimapped will not be selected if there are uniquely aligned reads at the same position. It would be possible to optionally turn off this feature but this wouldn't help you with your analysis. This is because our _dedup_ will not guarantee to return all the alignments for a given read since it deals with each position independently. 

Imagine a read aligned to 2 positions. In one position there are many other reads aligned so which read(s) get retained depends on the UMIs observed and the method used. In the other position it is the only read aligned and so will always be retained. In this instance one of the alignment positions may not be retained in the final outputted BAM. 

I think the only way you will be able to incorporate UMI-Tools into your current workflow is to generate a BAM with a single alignment per read prior to the deduplication. There are tools such as [Butter](http://biorxiv.org/content/early/2014/07/23/007427) which identify the "best" single alignment using the distribution of prior alignments . Alternatively, you could implement your own iterative mapping processs. I've done this in the past so I have some code I can share?

**Comment by IanSudbery** [comment]
Hi Camile,

An alternative would be to pre-process your BAMs to set the NH tag to 1 in all cases. Thus you would effectively eliminate the number of mappings as a criteria for selecting reads.

**Comment by TomSmithCGAT** [comment]
@IanSudbery This would still result in a final BAM which was incompatible with the downstream analysis if any method other than "unique" is used as some reads will lose their multiple alignments. I think the multiple mapping issue ideally needs to be dealt with prior to UMI-Tools.

**Comment by casimonet** [comment]
Hi,

Thank you for your answers.
Even if I remove the number of mappings as a criteria for selecting reads, if I have let's say two reads (a and b), having a different UMI due to sequencing/PCR error, both mapped to two positions. Since each position in treated independently, I could end up with read a selected at the first position and read 2 selected at the second position, thus having two distinct reads uniquely mapped, while initially it was only one, PCR duplicated read, which should be multi-mapped.
If I understand correctly, this was the point of Tom?

I am wondering if a similar problem could not arise if I a BAM with a single alignment per read prior to the deduplication.
If I directly do an alignment not allowing for multi-mapping, about 20% of my reads will not map.
If I select the best single position afterwards, it might result that at the best position of read a is the first position and the best position of read b is the second. I will again end up with two different and uniquely mapped reads. And in this case there is nothing to deduplicate.

@TomSmithCGAT  I am not sure about what you mean with an iterative mapping process. I would be very interested by some code if you are fine with sharing it.

**Comment by TomSmithCGAT** [comment]
@casimonet That's a very similar, related issue. Essentially because dedup considers each position independently, quite a few unwanted results can arise if you have multimapped reads.

As I see it you have two choices:

1.  **Only report a single alignment position per read**
Iterative mapping should give you a better alignment position than simply taking a random position from the N best. I'd recommend trying Butter first as it's a command line tool so you can use it out of the box. If you're not happy with the results and want to tweak the iterative mapping, I can share my python code which is essentially doing the same thing as Butter.

2.  **Report multiple alignments and implement bespoke deduplication**
There is a very nicely explained example of how to use UMIs to resolve multiple mappings in the  [inDrop sequencing paper](http://www.sciencedirect.com/science/article/pii/S0092867415005000). I've copied the relevant section from the sup. methods below. For your purposes, you would be considering alignment positions rather than genes.

_To illustrate the UMI filtering step, consider a single UMI present in two reads, the first aligning to genes A and B and the second aligning to genes B and C. Although neither read aligns unambiguously, gene B alone can explain the presence of both reads and thus the alignments to genes A and C are discarded, and just one of the two reads is kept for gene B_

_Each distinct UMI is associated with a set of genes through the set of reads carrying the UMI. For each UMI, we identified the minimal set of genes that can account for the full set of reads with this UMI. This problem is known as the ‘Hitting Set Problem’ (or ‘Set Cover Problem’) (7). We applied a greedy algorithm (8) to obtain the most parsimonious gene set for each UMI. For this final gene set, we kept only one read per gene per UMI. With this approach, some subsets of genes may still be undistinguishable from each other because they are supported by the same set of ambiguously aligned reads.  Finally, (5) if a read still aligned to more than 2 genes after UMI filtering, we excluded the read altogether_

**Comment by casimonet** [comment]
Ok I'll see what I can do with this.

Thank you very much for your answers,
C.
