### ISSUE TITLE
ddseq/surecell regex + whitelist

### ISSUE THREAD

**Issue by baffiak** [CGATOxford/UMI-tools#342]
Hi, I've updated a little bit regex code for ddseq/surecell, because I think it's not optimal that one, which is in your FAQ - it's missing information about possibility of the PhaseBlock at the beginning of the Read1 (the number of identified reads with barcode is similar with results from BaseSpace)

`(?P<discard_1>.{0,5})(?P<cell_1>.{6})(?P<discard_2>TAGCCATCGCATTGC){e<=1}(?P<cell_2>.{6})(?P<discard_3>TACCTCTGAGCTGAA){e<=1}(?P<cell_3>.{6})(?P<discard_4>ACG)(?P<umi_1>.{8})(?P<discard_5>GAC).*`

However, I have a question about possibility to use whitelist during whitelist generation:
Methods like a 10x and ddSeq have a list of all of the possible correct Cell Barcodes. Is it possible to somehow implement usage this list during generating of the whitelist?

Thanks

Pavel

**Comment by IanSudbery** [comment]
Thanks!

If you have a list of known true barcodes, then you can present them to `extract` with `--whitelist=`. Normally with a known whitelist, the use of the `whitelist` step isn't necessary, as the job of this is to find the real barcodes. If you want to use the `whitelist` tool but still make use of the known whitelist, I recommend you run `whitelist` and then intersect the resulting list of barcodes with your list of known barcodes before providing it to `extract`.

**Comment by baffiak** [comment]
Hi,

yes, it's true. However, ddSeq/Surecell similarly as 10x have list of all possible correct cell barcodes (BC1 + BC2 + BC3, for each 96 combinations, in total 884.736 different combinations). When I've used a umi_tools extract, 297 from 365 identified BC1 were not in the list of correct barcodes (BC1 comes from first bases from read1, it's normal there is higher error rate, which should be error corrected)

So, I think implementation of comparison with "possible barcode list" can improve usage of umi_tools for analysis with libraries from 10x or ddSeq.

I like a umi_tools very much, it's doing a great job for processing of UMIs. However, this is a little bit limitation for processing of data from this type of droplet-based single-cell sequencing methods.

Thanks

**Comment by IanSudbery** [comment]
It is possible to pass a list of whitelisted barcodes, and barcodes to be corrected to one of the whitelisted barcodes to `extract` as a two column file, as described here: https://umi-tools.readthedocs.io/en/latest/reference/extract.html#filtering-and-correcting-cell-barcodes.

At the moment you can have `whitelist` generate a file like this using the most frequently observed CBs within a cluster of related CBs by using `--ed-above-threshold=correct`. Presumably you could use this and then only accept corrected barcodes that are present in the list of allowed barcodes. 

Or you could generate the file yourself by listing all the possible CBs in the first column, and all CBs within one edit of them in column 2. 

We do not intend to develop the whitelisting procedures in umi_tools further because we feel that to do the job properly would take a complete overhaul of all CB related alogrithmns, and probably the development of new ones. `alevin` is one example of a tool that does this much more intelegently than we do, and we recommend its use if your data is compatible. While I don't believe alevin is currently compatible with ddSeq, hopefully that will change with time.
