### ISSUE TITLE
Produce consensus read

### ISSUE THREAD

**Issue by chadisaad** [CGATOxford/UMI-tools#359]
Is it possible with UMI-tools to produce an consensus read for each UMI-family instead of choosing the one with the best MAPQ ?

**Comment by IanSudbery** [comment]
As per our FAQ (https://umi-tools.readthedocs.io/en/latest/faq.html), this functionality is not currently implemented. The best we can offer at the moment is that rather than using `dedup` you use `group` and then post-process to get all the reads that belong to the same UMI family and create your own consensus from them. 

If you are interested in creating this functionality, we welcome pull-requests, and are happy to help people finding their way around the code base, but non of us currently has the time or background to do a good job of implementing this ourselves.
