### ISSUE TITLE
I need a bam file that contains an error corrected molecular barcodes as a TAG named UB or XM. 

### ISSUE THREAD

**Issue by sarajimenez** [CGATOxford/UMI-tools#381]
Hello, 

I'm sorry, I have a very basic question ...

I need a bam file that contains an error corrected molecular barcodes as a TAG named UB or XM. Specifically for running velocyto. 

I've been struggling to try to add this modifying several options with the command _count_.  

Right now my bam file looks like this:

`K00201:191:HNVFNBBXX:1:1225:27600:17034_GTGAGTGA 272 chr1 3329451 1 48M12S * 0 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATCACTCACAGCACGGTTA A<-FF<FAAA7-7--J<F-JFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA NH:i:3 HI:i:3 NM:i:1 MD:Z:45G2 AS:i:45 nM:i:1 jM:B:c,-1 jI:B:i,-1`

And I need somethis like this: 

`K00201:191:HNVFNBBXX:1:1225:27600:17034_GTGAGTGA        272     chr1    3329451 1       48M12S  *       0       0     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATCACTCACAGCACGGTTA     A<-FF<FAAA7-7--J<F-JFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA   NH:i:3  HI:i:3  NM:i:1  MD:Z:45G2       AS:i:45 nM:i:1  jM:B:c,-1       jI:B:i,-1       UG:i:0  XM:Z:GTGAGTGA`

I'd highly appreciate your help!

Have a nice weekend.

**Comment by IanSudbery** [comment]
If you use `group`, with `--out-bam` rather than `count`, then the error
corrected output will be added to the read as tag BX. See
https://umi-tools.readthedocs.io/en/latest/reference/group.html

Now I can think of several ways of renaming this tag `BX`, but they all
feel a bit clunky. Here is how I would do it, using a python program and
pysam:

```python
import pysam
bamfile = pysam.AlignmentFile("mybam.bam")
with pysam.AlignmentFile("mybam_processed.bam", "wb", template=bamfile) as
outfile:
     for read in bamfile.fetch(until_eof=True):
          umi = read.get_tag("BX")
          read.set_tag("UM", umi)
          outfile.write(read)
```

**Comment by IanSudbery** [comment]
If you use `group`, with `--out-bam` rather than `count`, then the error
corrected output will be added to the read as tag BX. See
https://umi-tools.readthedocs.io/en/latest/reference/group.html

Now I can think of several ways of renaming this tag `BX`, but they all
feel a bit clunky. Here is how I would do it, using a python program and
pysam:

```python
import pysam
bamfile = pysam.AlignmentFile("mybam.bam")
with pysam.AlignmentFile("mybam_processed.bam", "wb", template=bamfile) as
outfile:
     for read in bamfile.fetch(until_eof=True):
          umi = read.get_tag("BX")
          read.set_tag("UM", umi)
          outfile.write(read)
```

**Comment by TomSmithCGAT** [comment]
You can run `umi-tools group --out-bam` as @IanSudbery suggested but also include the option `--umi-group-tag=UB` to set the output tag to `UB`. This option is visible through the command line help but not the online documention which is an oversight
