### ISSUE TITLE
scRNA seq tutorial under ".../docs" concatenates all input fastq files. How to make pairwise comparison between case and control later on, then?

### ISSUE THREAD

**Issue by vyturing** [CGATOxford/UMI-tools#386]
Hello,

I am a big fan of UMI-tools and have a couple quick generic questions. In the UMI-tools scRNA seq tutorial within section "Step 1: Obtaining the data", all 8 read2 fastq files from different lanes are concatenated. 
1. Are all these biological or technical replicates (Let's assume these data were of an original publication and I followed the tutorial step-by-step)?
2. Can one have a control or replicate in a scRNAseq experiment given that each cell included behaves differently and that this question is intuitively against the nature of scRNAseq?
3. Assuming that you want to make a pairwise comparison between case and control in a scRNAseq experiment. How would you make the comparison later on in the analysis pipeline if you already combined all input fastq files and made a single alignment for both groups together?
4. How should one start off the analysis pipeline with multiple input fastq files; concatenating all these fastq files that have read sequences BEFORE alignment or performing 6 different alignments for each of the input files separately and afterwards combining the final count matrices? Does it make any difference regarding the output?

These are very critical questions I need to have an answer for so that I can literally understand the basics of the scRNAseq analysis pipelines. I look forward to your reply!

Thank you so very much for the time and the effort!!

Cheers :-)

**Comment by IanSudbery** [comment]
Thanks for your interest!
Some of these questions are outside the area's I'm an expert in, but I will try to answer best I can. In the example in the single cell tutorial, if different files are from the same library split over multiple lanes. 

That is - the 10x machine was run, and the a tube of library produced, and then 8 allquots of this library were run on 8 different sequencing lanes in order to generate sufficient reads for the sample. So these are the most technical of technical replicates, in that the reads in file 1 can come from the same cell as those in file 2 (and 3,4,5 and so on). 

It is possible to treatment/control and replicates in scRNA - imagine doing scRNA-seq on a sample of cells from a patient with a disease and scRNA-seq on a health patient. For replicates imagine taking a sample blood cells from me and doing scRNAseq, and then a sample of cells from you and doing the same.

However, in these cases, I would not combine the input files. If there were different replicates/conditions in your experiments, I would process, map and dedup each sample seperately without combining the files - I would only combine the files where they were, as in this case, the same library split across multiple sequencing lanes. 

Hope this helps.

**Comment by vyturing** [comment]
That helps a lot! Thank you so very much, Ian and also for this amazingly clear answer that is highly detailed. Now I have a holistic grasp of scRNA-seq. Knowing all the details but missing the big picture bothered me here. Much appreciated!
