### ISSUE TITLE
Error when importing network.py module

### ISSUE THREAD

**Issue by gamabunta313** [CGATOxford/UMI-tools#413]
I would like to exploit your network.py module for UMI handling. However, after imported umis as both list and dict (umis=["AAAA"] and counts={"AAAA":3}, threshold=2) I ran it having the following error:
"TypeError: __call__() takes 3 positional arguments but 4 were given". 

I used your suggested code to test the algorithm:
from umi_tools.network import UMIClusterer
clusterer = UMIClusterer(cluster_method="directional")
clusters = clusterer(umis, counts, threshold)

I thank you in advance for your help

**Comment by IanSudbery** [comment]
The UMIClusterer code has been changed so that you call it:

clusters = clusterer(umis, threshold)

This is reflected in the documentation on the readthedocs:
https://umi-tools.readthedocs.io/en/latest/API.html#the-umiclusterer-class

We must have missed changing the documentation somewhere else.

Can you let me know where you found
clusters = clusterer(umis, counts, threshold)

from so that we can fix the documentation?

Cheers.

**Comment by gamabunta313** [comment]
I realized that it was an old post. Following suggestions on the readthedocs I did it. Thanks for your help.
