### ISSUE TITLE
a way to pre-split barcodes for running parallel instances of the group function

### ISSUE THREAD

**Issue by OldManTae** [CGATOxford/UMI-tools#417]
Hello,

First of all, thank you for this great tool - I have been using it throughout my PhD work over the years and it has been a great tool!

I am currently trying to apply the group function on a region that contains a lot of unique umis. Because of this, it has become a bottleneck in my code where even with 100G+ and 3 days of computing, the program fails to finish on time. From what I gathered, there isn't a plan to enable multi-threading for the group function directly, but is there a way to pre-split the barcodes into chunks that I can run across many different jobs (for instance, a way to use the output of multithreaded deduplication to pre-split the data and run)

I wanted to hear of any ideas when you were considering implementing multi-threading the group function, as it might save me considerable amount of time trying to reinvent the wheel

Alternatively, is there a smaller portion of the code that I can use to perform grouping on just a list of barcodes (presumably save on memory that way and maybe speed things up)

Thank you in advance for your time!

**Comment by IanSudbery** [comment]
Hi, 

The obvious way to parrallelize would be to split out different genomic locations - say divide chromosomes or genes into different files and run on each. 

The way UMI-tools works is that one routine bundles reads into sets that could be duplicates - this generally means that start at the same location/map to the same gene, are on the same strand, (maybe) have the same introns. The returned bundle contains the unqiue key which specifies its identity as a bundle (generally a combination of genomic location, insert size,  strand, and intron locations), the UMIs detected at that location, the count for each UMI, and a representative read for each UMI (or a list of reads if you are grouping rather than deduplicating). 

As each bundle is returned from the bundle generator, it is sent to the UMI processor. When the bundle returns from the UMI processor the approriate reads are sent to the output routines (which involves keep a list of the read2s that need outputting in the case of pair-end sequencing). 

There are three parts in common to all the UMI processing step: calculating the edit distance between all the UMIs in the bundle, using this to construct a network, and using the network to group the UMIs. Because the edit distance calculation is called so many times, it is the obvious place to parralelelize, but it turns out that the overhead associated with doing this is greater than the beneift.

The next more obivous place to parrallelize is at the level of bundles, as they stand independent of each other. However, you can't pass bundles as they are to a process pool in python because some parts of the bundle (primarily the reads themselves) can be serialized. 

The solution would be to separate the UMIs and counts from the rest of the bundle, send them off to multiprocessing queue and reunite them with the rest of the bundle when they return. As things don't necessarily come out of a multiprocessing queue the same order as they went in, it would be necessary to find some way of matching them up. 

> Alternatively, is there a smaller portion of the code that I can use to perform grouping on just a list of barcodes (presumably save on memory that way and maybe speed things up)

Yes! See here in the documentation: https://umi-tools.readthedocs.io/en/latest/API.html

However, I don't know how much memory will be saved. In group too things take memory
1) Holding all the reads not yet outputted in memory
2) Holding the UMI graph in memory. 

I know that an UMI graph for a bundle can take more than 100G in a pathological situation: If you have 1M UMIs at a location, and they are all connected to each other, that 10^12 connections that are stored! But it might be worth a try.

**Comment by ZKai0801** [comment]
Hi @IanSudbery  and @OldManTae,

I managed to write a pipeline that can enable multithreading in a simple manner. This might be able to help you with your project @OldManTae . @IanSudbery Could you please take a look at my pipeline to see if it makes sense.

Assuming you have paired end fastqs

```
sampleID=$1
thread=$2

# Split fastq files for multithreading extract process
gunzip -c ${sampleID}_R1_001.fastq.gz |split -l 800000 - ${sampleID}_R1.tmp.
gunzip -c ${sampleID}_R2_001.fastq.gz |split -l 800000 - ${sampleID}_R2.tmp.
ls ${sampleID}_R1.tmp* | xargs -i -P ${thread} sh -c 'fq1={}; fq2=${fq1%R1*}R2${fq1##*R1}; umi_tools extract --extract-method=string -I $fq1 --read2-in=$fq2 --bc-pattern=NNNNNNC --bc-pattern2=NNNNNNC --stdout=${fq1}.umi --read2-out=${fq2}.umi'
cat ${sampleID}*R1.tmp*umi >${sampleID}.R1_umi.fastq
cat ${sampleID}*R2.tmp*umi >${sampleID}.R2_umi.fastq
rm ${sampleID}*tmp*

# then trim and map your reads
# trimmomatic / bwa etc..

# once get the BAM file, split the BAM based on chromosome
samtools view -H ${sampleID}.sorted.bam |grep "@SQ" | awk '{print $2}' |awk -F':' '{print $2}' |xargs -i -P ${thread} sh -c 'samtools view -b ${sampleID}.sorted.bam {} > ${sampleID}.tmp.{}.bam'
ls ${sampleID}.tmp*bam |xargs -i -P ${thread} sh -c 'samtools index {}'
ls ${sampleID}.tmp*bam |xargs -i -P ${thread} sh -c 'umi_tools dedup -I {} --paired -S {}.dedup.bam'

# merge all sub-BAM into a compact BAM
samtools merge -@ ${thread} ${sampleID}.dedup.bam ${sampleID}.tmp*dedup.bam
rm ${sampleID}.tmp*
```

**Comment by OldManTae** [comment]
Thank you for your reply Ian

Unfortunately my situation is more of the pathological case, where I have many millions of umis at one single location. So it sounds like even the bundling wouldn't help since all my umis would be considered duplicates from what you describe

To try to get around this problem, I have 2 questions:

1. Would count be any faster than group? From the readme/tutorials, it seems like computation wise, group essentially performed for count, except count is much less memory intensive. However, I get the feeling count may perform faster - is this true? If so, is it much faster, then how by much?

2. Is there a major technical issue with randomly shuffling the data into multiple segments, performing group/count in the subsets, and then merging the results? (perhaps doing some clustering of the final umis of the subsets if need be). It seems like the grouping function shouldn't need to see all the barcodes to converge on final umis (when there a lot of barcodes and duplicates of the barcodes), and perhaps a less sophisticated round of clustering (maybe just by hemming distance) in the second round would merge larger clusters together fine.

I just thought I would ask in case you looked at this when considering different implementation options. Any advice would be greatly appreciated!

**Comment by OldManTae** [comment]
Just an update on this for anyone who might run into a similar problem. I tried two different methods with varying results:

1. I tried using an alternative algorithm (DNAclust) to deal with the memory and time run time issues. It worked to an extent in that it could run the entire list of reads without issues. However, a problem that I ran across was that since this is a greedy algorithm, the clustered barcode would not cluster consistently across replicates. It might be possible to fix this by playing around with k-mer sizes, but for the time being I decided to go back to modify my use of umi_tools

2. I tried splitting the bam file (keeping paired reads together) into 10 smaller files, and then performed the clustering/grouping. This worked very well for the most part, but I did notice that some of the rarer barcodes (< 10) had issues, where they tend to become singletons. I presume this is because rare barcodes are spread across the subset files, so the clustering did not work well within each individual subset.

So depending on your needs, I think the subsetting of the bam files could work (if there is are major issues with memory or time), but note that rarer barcodes will perform poorly, depending on how much you split the file. I needed to do this since I running the whole file will probably require a lot more than 10x the resources.

One idea that might work would be to use a fast algorithm to roughly split the barcodes by similarity, and then apply the directional algorithm to avoid unnecessary barcode comparisons for barcodes that are very different from each other (though a better way might be to design the experiment differently to avoid this situation)
