### ISSUE TITLE
Silent out of bounds failure 

### ISSUE THREAD

**Issue by pati-ni** [CGATOxford/UMI-tools#424]
`umi_tools extract` fails with an out of bounds exception when read is shorter than `--bc-pattern`

An option that ignores such reads would be useful in processing such files.

Currently on illumina reads, the workaround is to re export fastq files with `bcl2fastq` which requires extra software along with the bcl files.

**Comment by TomSmithCGAT** [comment]
Hi @pati-ni - Sorry for the very delayed reply here.

Can you confirm how the read length comes to be shorter than the bc-pattern in the first place? Is this due to trimming of the reads before UMI extraction and if so, is the trimming done within bcl2fastq and hence the need to re-export with `bcl2fastq`?

If this is the case, I would argue that the input to `umi_tools extract` is pretty poorly generated in the first place. I would prefer to see this resolved by exporting with `bcl2fastq` with `-minimum-trimmed-read-length` set to a more suitable value, or else read trimming performed post UMI extraction. I think handling this within `umi_tools extract` is probably getting outside of the functionality it should cover. Thoughts @IanSudbery?

**Comment by IanSudbery** [comment]
We should probably at least have a better error message.

**Comment by TomSmithCGAT** [comment]
Yep. Very good point. Let's leave this open until that is addressed.

**Comment by TomSmithCGAT** [comment]
This was resolved with PR #433
