### ISSUE TITLE
--filter-out and --filter-out2

### ISSUE THREAD

**Issue by nktkee** [CGATOxford/UMI-tools#437]
Hi,

I'm wondering how to get the --filter-out option working, where reads that don't match a UMI are sorted out into a separate file?

cheers,
nk

**Comment by TomSmithCGAT** [comment]
You should just need to add the argument `--filtered-out=FILENAME`, replacing FILENAME with the path to where you wish to write out the filtered reads. If you have a paired input, you will need `--filtered-out2=FILENAME2` also.

**Comment by TomSmithCGAT** [comment]
@nktkee - Did you get this working OK?

**Comment by Evelyn2579** [comment]
I have the same problem with nk. I used `--filtered-out=filename`, but it reported an error: `extract: error: no such option: --filtered-out`. 
also wondering how to get the argument `--filtered-out=filename`  work

**Comment by TomSmithCGAT** [comment]
@Evelyn2579 - That's

**Comment by Radek91** [comment]
I face the same issue. The option seems to have vanished (including from the -h help).

`UMI-tools version: 1.0.1`

**Comment by TomSmithCGAT** [comment]
@Radek91 - You're right. The PR with this option (#330) wasn't merged until 13 AUG 2020, and no release was made until `1.1.0` on 03 NOV 2020, which explains why this option wasn't available to @Evelyn2579 & @nktkee, who I assume installation via `pip` or `conda`. I'd overlooked the difference between the master branch and the latest release.

Since the option is now available on the latest release, I'll close this issue now. If anyone else is having the same problem, please make sure you are using version >= 1.1.0.
