### ISSUE TITLE
Dedup by per-gene 

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/UMI-tools#44]
Currently, dedup can work on a per-position or per-contig basis.The per-contig method is implemented for single cell RNA-Seq methods such as e.g CEL-Seq where the position of the read on a transcript may be different for reads generated from the same initial molecule. However, this requires that the reads be aligned to a single contig, i.e a representative gene model. Ideally we would like to align to all transcripts and give dedup a file mapping contigs (transcripts) to meta-contigs (genes) and introduce a "per-meta-contig" method. 

This is straightforward to implement within UMI-Tools dedup but requires the bam to be sorted by a meta-contig feature which I don't think is possible with standard command line tools. We could of course make a new command umi_tools sort to perform the sort using pysam?

@IanSudbery - thoughts?
Biostars question on custom sam sort tool [ here](https://www.biostars.org/p/208599/)

**Comment by IanSudbery** [comment]
Is it neccesery to sort the BAM before hand? Could we not just, for each gene, run a fetch with a list of contigs associated with each meta-contig? Something like:

```python
def metafetcher(bamfile, contig2metacontig):

    def _inner(metacontig):
          for contig in contig2metacontig[metacontig]:
              for read in bamfile.fetch(contig): 
                   read.contig = metacontig
                   yield read

    return _inner


if options.per_gene:
      fetcher = metafetcher(in_bam, gene2transcript)
else:
      fetcher = pysam.fetch

```

It would of course require an indexed bam as the input rather than being able to read off the stdin.

**Comment by TomSmithCGAT** [comment]
Yup, that's much simpler!

**Comment by inakicm** [comment]
Hi,

Thanks for UMI_tools, and sorry if this is a silly question:

I can not use the per-position method because we used a protocol where the position of the read on the genome may be different for reads generated from the same initial molecule. 
I made the mapping using HTseq-count, so after the mapping I get a TAG (XF) in the SAM file which gives me the gene name for each read. So instead of working with the per-position method, is it possible to simply give a TAG (which corresponds to the gene name) to the deduplication procedure? In this way, the UMI deduplication works directly on the gene and not on the position.

Thanks,
Iñaki

**Comment by IanSudbery** [comment]
Hi Inaki,

We currently support per-gene deduplication where the gene name is stored in the contig column of the BAM file - this is what you get when you map to the transcriptome, rather than to the genome.  There are a couple of wrinkles with the process that makes using a tag difficult. Mostly that the BAM file would have to be ordered by that tag. It is something we could do, but I don't have time to implement it at the moment. 

I recommend you either remap your reads to the transcriptome, and run UMI_tools  with `--per-contig`. You could also reformat the BAM to transfer the gene name form the tag to the contig, sort by contig, reheader and reindex. Or wait until either I or @TomSmithCGAT find some time to implement using a tag. No promises on when that might be though. 

Sorry I couldn't be more help. 

Ian

**Comment by inakicm** [comment]
Ok, thanks for the explanation!
I will reformat the BAM file.

Best,
Iñaki

**Comment by MarinusVL** [comment]
Hi,
I'm also interested in dedup per gene so thanks for the suggestions on how to make it work by reformatting the bam. I just wanted to put two options out there to maybe get this implemented sooner. The sam file with the XF gene_id tag from htseq can simply be sorted with a unix sort so could perhaps the tag based dedup be implemented without much work on your side by specifying the tag and requiring that the user supplies a correctly sorted bam? 
Another option that would make sense is not to dedup the bam file, but dedup the output from the counts script. since otherwise reads would need to be counted twice, first to pool features to genes, dedup and then count another time to get the gene counts. Featurecounts, and there is now also VERSE, provide a tab-delimited file that contains four columns including read name, status, name of target feature/metafeature and number of hits. Running the dedup on this would make the second counting step unnecessary. And if implemented would make umitools more versatile, as any tab-delimited file containing a UMI in the first column and a user specified second column to sort on can then be deduped.

Best, Marinus

**Comment by TomSmithCGAT** [comment]
Hi @MarinusVL. Thanks for the suggestions. I've added per-gene deduplication to our TODO list for the next version so we'll have a look at this shortly.

**Comment by MarinusVL** [comment]
Great looking forward with what you come up with. Something that would handle the featurecounts tab file would be nice as it is so much faster compared to HTseq.

**Comment by MarinusVL** [comment]
Hi Tom,

That's great.I'm not sure I've time this week but next week should work to
give these a test run. Thanks for implementing this so quickly. I'll run
them on cellseq2 data from HT-seq processed files and an aligned to
transcriptome bam file from STAR

best regards, Marinus

2017-02-28 9:17 GMT-08:00 Tom Smith <notifications@github.com>:

**Comment by darachm** [comment]
Tiny issue I may be overlooking, but might help with clarity in documentation (unless I missed it) of this very useful feature in a very useful tool:

By "per contig" in "--per-contig", do you refer to field 3 in a SAM file (converted to BAM of course), that is "RNAME" or "Reference sequence NAME"?

**Comment by TomSmithCGAT** [comment]
Hi @darachm. Thanks for the suggestion. You're correct that the per-contig option refers to the third column. I'll update the documentation to make this clear.

**Comment by TomSmithCGAT** [comment]
Closing this issue. For future developments with per-gene read counting see #114
