### ISSUE TITLE
Number of reads supporting each UMI

### ISSUE THREAD

**Issue by KaiyangZ** [CGATOxford/UMI-tools#45]
Hi,

Is a way to output the number of reads that support each UMI before and after deduplication?  It is useful for check the quality of the data.

Thanks!

**Comment by IanSudbery** [comment]
Hi,

I believe that --further-stats will output the number of times each UMI sequence is used before and after deduping, but I presume you mean for each position/gene? Thats not currently a feature, but I can see how it would be useful. We'll consider adding it in the future, I don't think it could be too hard.

**Comment by KaiyangZ** [comment]
Yes, it would be nice it can be available for each position/gene.  Thanks a lot! 

    On Friday, August 26, 2016 1:14 PM, Ian Sudbery <notifications@github.com> wrote:
 

 Hi,I believe that --further-stats will output the number of times each UMI sequence is used before and after deduping, but I presume you mean for each position/gene? Thats not currently a feature, but I can see how it would be useful. We'll consider adding it in the future, I don't think it could be too hard.—

**Comment by TomSmithCGAT** [comment]
@KaiyangZ The _group_ branch includes a new command _group_ which allows you to use the network methods to group the reads c2f6e81 . When run with the ``--group-out = <outfile>`` option the tool will generate a file mapping read identifiers to a unique group for each set of reads with the same genomic position and UMI(s). You can extract the number of reads that support each UMI before and after deduplication using this output (even though it's not actually de-duplicating the BAM) since the "final_umI" column is the UMI which would be selected for that group of reads using the chosen method:

`umi_tools group -I example.bam --group-out=test.tsv`

`head -5 test.tsv`

read_id contig  position        umi     count   final_umi       unique_id
SRR2057595.6698198_CATAC        chr1    3090327 CATAC   1       CATAC   0
SRR2057595.2503884_CAGAT        chr1    3605682 CAGAT   1       CAGAT   1
SRR2057595.118137_TCATA chr1    3605683 TCATA   185     TCATA   2
SRR2057595.135718_TCATA chr1    3605683 TCATA   185     TCATA   2
