### ISSUE TITLE
UMIClusterer speed on large dataset and potential parallelization 

### ISSUE THREAD

**Issue by coffeebond** [CGATOxford/UMI-tools#451]
Hi,

Thanks for developing this fantastic tools. 

I am using the UMIClusterer API to collapse a large amount of sequenced barcodes. I found the speed reduces dramatically when the number of unique barcodes becomes larger. For example, it takes about 1 hours to cluster ~450,000 unique barcodes (pretty impressive) but the time jumps up to ~10 hours for 1,400,000 unique barcodes. I have some datasets that have ~4,000,000 unique barcodes and it's been many days since the run started.

I understand this is inevitable for the clustering when the number of unique barcodes increases, but I wonder if there is a way to speed it up, for example, by implementing parallelization. I imagine that this wouldn't be easy because the algorithm needs to create a whole network of the complete dataset. I'd appreciate if you can share some insights of how to resolve this problem.

I am using the "directional" method and asking for the threshold of 1.

Thanks!

**Comment by IanSudbery** [comment]
We did try some simple parallelism - sending individual comparisons to a pool of worker processes, but the overhead on this proved to be greater than the speed increase gained, and the parallel version of the algorithm was actaully slower than the single threaded version. There might be some mileage to be had in bundling up comparisons into batches and sending them as as batches to worker processes.

It should also be possible to send entire locations to worker processes in parallel. So while a 1.4million barcode location would still take 10 hours, if you had two of them, the whole thing would still only take 10 hours, rather than taking 20. The main problem here would be that the locations woulnd't necessarily come back in the order they were sent, so you'd need some way of marrying the results up to the read bundle when it came back. 

 Finally, we know there are improvements in the algorithm itself that could be implemented, but we haven't had time to implement. At the moment we use either a naieve all by all edit distance implemention, or a n-gram implementation depending on the size of the UMI list. Daniel Liu showed that a n-gram of bk-trees is faster at high levels of network complexity (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6921982/).

**Comment by coffeebond** [comment]
Thanks for the response. 

My barcode is relatively long (20nt) so I guess it makes this process even slower. I can definitely divide the dataset into 20 worker processes, but I haven't figured out a good way to merging the clusters. 

I will take a look at the paper you mentioned and see if I can implement that.
