### ISSUE TITLE
Converting UMI-Tools output into correct format for cHiC analysis

### ISSUE THREAD

**Issue by aturocks** [CGATOxford/UMI-tools#490]
Hello,

I'm doing a capture HiC experiment where the reads contain adapters with a 11bp UMI. Right now I'm using HiCUP to process and filter the data, but I wanted to utilize UMI-tools (instead of the inbuilt HiCUP deduplicator) to deduplicate the filtered BAM file before moving on to downstream analysis with CHiCAGO. 

I have successfully deduplicated the files using UMI-Tools (attached below) but I think this deduplicated version is in an incorrect format, because I cannot build a .chinput (CHiCAGO input) file from this BAM. I am attaching the correct BAM format (from the default HiCUP deduplicator) as well.
[Dedup.hicup.bam.gz](https://github.com/CGATOxford/UMI-tools/files/7304336/Dedup.hicup.bam.gz)
[UMITools_dedup.bam.gz](https://github.com/CGATOxford/UMI-tools/files/7304338/UMITools_dedup.bam.gz)

Do you know how to convert the deduplicated BAM file from UMI-Tools to the correct format?

Best,
Atreyo

**Comment by IanSudbery** [comment]
Hi Atreyo,

The format looks identitical. I can't see much in the way of difference between these two files, with the exception that the hicup deduplciated file has fewer reads in it. This is a bit weird because I'd expect the file deduplicated with error correction to have fewer reads rather than more. Is it possible that hicup has done some other filters on the file?

I don't have any experience of either HiCUP or CHiCAGO. Do you get an error of some sort when you try to build the .chinput file?
