### ISSUE TITLE
comparison with alevin.

### ISSUE THREAD

**Issue by mortunco** [CGATOxford/UMI-tools#504]
I asked the same question in COMBINE-lab Gitter chat. Sorry for the duplication.

Hello,

Umi_tools recommends alevin for processing chromium data. I have V3 based single cell data. I am trying to use both softwares for only cellB correction. I observed a 379 CBs when I ran alevin with (noQuant) compared to 169 CBs from umi_tools (default settings, V3 bc pattern). I know this is a general question but I was wondering how should I attack this problem to figure out correct set of CBs.

```
### Alevin 
./salmon-1.6.0_linux_x86_64/bin/salmon alevin -l ISR --index capture/ --chromiumV3 -p 16 --tgMap tx2gene  --dumpfq --noQuant -1 R1.fastq.gz -2 R2.fastq.gz -o default-settings > default-settings.fastq
### umitools whitelist 
umi_tools whitelist --stdin ../NL2_CKDL210021281-1a-SI_GA_A2_HMHFJDSX2_S3_L004_R1_001.fastq.gz --bc-pattern=CCCCCCCCCCCCCCCCNNNNNNNNNNNN --log2stderr > umitools/default-whitelist
```

Thank you very much for help,

Best regards,

Tunc.

**Comment by TomSmithCGAT** [comment]
Hi Tunc.

This is a tricky question, and frankly, one that others may be better placed to answer.

The two tools take very different approaches to determine the best set of CBs.

- UMI-tools: Tabulate the cell barcode counts and then identify the 'knee' in the plot of cumulative reads per CB. This was following the recommendation in the original Drop-Seq paper ([Macosko et al](https://www.sciencedirect.com/science/article/pii/S0092867415005498#appd003))
- Alevin: 2-step whitelisting. In step 1, the top CBs are selected by a similar, but more relaxed 'knee' method. Step 2 occurs post quantification for each CB and takes inspiration from [Petukhov et al](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1449-6). Copying directly from  'Final whitelisting (optional)' in the original alevin paper [Srivastava et al](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1670-y):  _'Petukhov et al proposed that instead of selecting a single threshold, one should treat whitelisting as a classification problem and segregate CBs into three regions: high quality, low quality, and uncertain/ambiguous. Here, high quality refers to the CBs which are deemed to be definitely correct, and low quality are the CBs which are deemed to most likely not arise from valid cells. A classifier can then be trained on the high- and low-quality CBs to classify the barcodes in the ambiguous region as either high or low quality'_. Importantly, the features used do no simply correlate with read counts and should therefore more fully describe correct CBs.

Personally, having implemented both approaches, I favour the alevin method. But I would want to do further QC on the CBs regardless. For example, using [EmptyDrops](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1662-y) to ensure you don't have CBs which are overly contaminated with background ambient RNA.

**Comment by mortunco** [comment]
Thanks Tom for explaining both method clearly. I think I need some time digest this information and implement empty drops to our QC. We are working on single cell implementation of multi parallel reporter assays so need to tweak our data for empty drops.

I am closing the issue now. to whom has some suggestion please feel free re-open and comment. I would appreciate any idea!

Best,

Tunc.
