### ISSUE TITLE
Minimum python version (>=3.5) needs bumping up

### ISSUE THREAD

**Issue by gmnelson** [CGATOxford/UMI-tools#511]
Just installed UMI-tools in a 3.6.0 conda environment and the tools weren't working, largely throwing errors related to 'PySlice_AdjustIndices' -- seems this was introduced in 3.6.1.

Re-installed in a 3.7.4 conda env and all seems to be working.

**Comment by IanSudbery** [comment]
Hi, 

Do you have a record of the full error message? I can't reproduce, but thats  mainly because right now I don't seem to be able to get matplotlib installed in a python 3.6 environment, which I'm addressing here: https://github.com/conda-forge/matplotlib-feedstock/issues/316

But by the sounds of it, your issue is different?

**Comment by TomSmithCGAT** [comment]
I believe this issue has been rectified now. Please open a new issue if not.
