### ISSUE TITLE
Conda issue: IndexError: list index out of range

### ISSUE THREAD

**Issue by CWYuan08** [CGATOxford/UMI-tools#536]
Hi, umi_tools has always been working for me, but suddenly when I tried to put together a pipeline, it came to this error, for any command I use after umi_tools, (e.g. umi_tools dedup..):

Traceback (most recent call last):
  File "/miniconda3/envs/umitools/bin/umi_tools", line 8, in <module>
    sys.exit(main())
  File "/miniconda3/envs/umitools/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 53, in main
    elif argv[2] in ["--help", "-h", "--help-extended"]:
IndexError: list index out of range

However, when I just type umi_tools, there isn't any error.

Do you know how I could resolve this? 

Thank you very much!

**Comment by CWYuan08** [comment]
Hi @IanSudbery, sorry to bother again, I'm still getting the same issue, what should I do to resolve this..? Thank you very much!

Best,
CW

**Comment by IanSudbery** [comment]
Hi,

You are getting this error because you are executing `umi_tools dedup` etc, without any other options, and `dedup` etc requirement than just the name of the tool. We have edited the code so that the help should be output in this situation (if you pull the latest version of the master branch), but even with the last released version, you can avoid this by typing `umi_tools dedup --help` in order to get the help.

**Comment by CWYuan08** [comment]
Dear @IanSudbery,

thank you. I see, it worked!

Best regards,
CW
