### ISSUE TITLE
ClusterAndReducer instance has no attribute 'get_adj_list'

### ISSUE THREAD

**Issue by JeroenMerks** [CGATOxford/UMI-tools#55]
File "UMI-tools-0.2.5/umi_tools/dedup.py", line 569, in __call__
    adj_list = self.get_adj_list(umis, counts, threshold)
AttributeError: ClusterAndReducer instance has no attribute 'get_adj_list'

**Comment by IanSudbery** [comment]
Hi Jeron,

This is most odd. Can you let me know the exact command line you were running - the get_adj_list method should be set based on the deduplication method.  Unless you are somehow setting a method which we don't implement (which shouldn't be possible), I don't understand.

**Comment by IanSudbery** [comment]
Also, where is this version installed from? Line 569 doe not contain the quoted code in the GitHub version.

**Comment by TomSmithCGAT** [comment]
@JeroenMerks If you use the option --method=adjacency does this solve the issue?

**Comment by TomSmithCGAT** [comment]
@IanSudbery By chance I just happen to have come across this issue on a recent branch from the master to set up testing. The issue is that the default method is "directional" and this version of umi_tools is expecting to see the method as "directional-adjacency". Unfortunately, on the master branch the option parser also wont allow you to see the method as "directional-adjacency" as it's not one of the choices! 

All the more reason to set up the testing properly to avoid my idiotic bugs...

**Comment by IanSudbery** [comment]
@TomSmithCGAT Does this mean that the code we submitted as supplimentary files to the publication and archived on zendo doesn't work?

**Comment by TomSmithCGAT** [comment]
@IanSudbery I'm afraid so. The change was made to reflect the shortening of the directional method name in the updated manuscript. I guess we need to contact them immediately to make them aware of this. I've modified the master branch to remove the bug and released the code as v0.2.6. Archive: https://doi.org/10.5281/zenodo.165403

**Comment by IanSudbery** [comment]
This also means that the pipelines aren't going to work either, as they refer to 'directional-adjacency' too

**Comment by JeroenMerks** [comment]
Thanks for the fast reply and fix!

I needed to add the shebang line "#!/usr/bin/env python" for the (Cython?) compilation of dedup.py to work. When I just installed 0.2.6, I didn't receive any errors...
