### ISSUE TITLE
--ignore-tlen slow running

### ISSUE THREAD

**Issue by alexander-e-f-smith** [CGATOxford/UMI-tools#557]
To avoid clipping issues in read2 that can alter 5' mapping start positions  of otherwise duplicated molecules (eg see issue #534), i'm looking at option " --ignore-tlen". However, analysis seems to run drastically slower with this option. Why would this be and this there a way around this?
Thanks once again for your help!
Alex

**Comment by IanSudbery** [comment]
Almost certainly this is because UMI-tools is considering a larger number of reads at once. Two reads with the same start position but different `tlen`s are put in separate read bundles. With `ignore-tlen` they will be put in the same read bundle. As the UMI-tools directional algorithm scales super-linearly with the number of UMIs in the bundle, this is presumably why its running more slowly.

**Comment by alexander-e-f-smith** [comment]
Thanks Ian. I have a hunch that a certain gene in my data (RNAseq  type data) that is highly expressed could cause this. Does the dedup tool consider position only when initially grouping / bundling then? Or are these bundles a factor of UMI and read1 start (when using --ignore-tlen). I had also wondered if you had though of an option to limit max numbers of reads in any one read bundle/group?
