### ISSUE TITLE
Release with https://github.com/CGATOxford/UMI-tools/pull/577?

### ISSUE THREAD

**Issue by akmorrow13** [CGATOxford/UMI-tools#578]
Hi all,

Thank you for helping me get started contributing on UMI-tools, I really appreciate it. Curious to when the next release on conda will be: we need https://github.com/CGATOxford/UMI-tools/pull/577 to calculate grouping statistics in our pipeline.

Happy to help if needed!

**Comment by TomSmithCGAT** [comment]
Hi @akmorrow13. There's no schedule for release - I wish we were that organised. The last release was May 2021 though since the last release and we have a few debugs added since then, so I'll try and get a release done today. There will be a slight delay between our release and bioconda, though usually it's just picked up by their bots and sorted quickly.
