### ISSUE TITLE
Impact of scaffolds/ERCCs AND/OR pre-defined UMIs on speed/accuracy

### ISSUE THREAD

**Issue by nmukherjee** [CGATOxford/UMI-tools#59]
Hi Ian and Tom,
I very much like the theory behind this tool and am trying to use it in my research. I realize I may be conflating two specific issues..if so I am sorry, but here goes anyway!

We have performed paired-end strand-specific RNA-seq with a [kit utilizing UMIs from BIOO scientific](http://www.biooscientific.com/Next-Gen-Sequencing/Illumina-Library-Prep-Kits/NEXTflex-Rapid-Directional-qRNA-Seq-Kit). As they state:  

"The NEXTflex Rapid Directional qRNA-Seq Kit contains a set of 96 distinct molecular labels on the sequencing adapters. Each label consists of an 8 nucleotide barcode tag. During the ligation reaction, each cDNA fragment independently and randomly ligates to a single label from this pool of 96 adapters to result in a total of 96 x 96 = 9,216 possible combinations across both ends."   

I have included the cartoon of the cloning strategy from their website below.

![image](https://cloud.githubusercontent.com/assets/2624452/20596626/c35149cc-b23f-11e6-93c3-ef6c688cdf4a.png)

## Problem:
I have been using umi-tools and the 'dedup' step takes a long time ( > 30hrs for 42 million reads). I have followed suggestions from earlier posts and do not output stats.

## Information:
Reads: ~ 30-40 million, paired-end 75 nt reads
UMI: 8 nt long on both pairs
Reference: human genome and **some scaffolds and ERCC sequences**
Alignment: star, limiting multi-mappers
version: umi-tools-0.2.3
umi method used: "directional-adjacency"
cpu: one node of compute cluster, 36G mem

## Observations:
I created two bam files using a subset of reads that map to either A) chr19 (104 M bam file) or B) the 92 ERCC RNA spike-ins (34 M bam file).

For chr19, the dedup process took 74 seconds.
2,428,230 before dedup
1,383,172 after dedup
**This is a non-trivial level of replication! Ideally I would like to test different umi dedup methods using ERCC counts and see what correlates the best with known ERCC concentrations.**

For ERCC, the dedup process has taken > 1hr and i killed it!!
894,572 before dedup
??? after dedup

The reason I tested this is when I cranked up the verbosity in the log I noticed that the dedup process was really getting bogged down once it got to scaffolds (~160 in my assembly) and ERCCs (92 spike-ins).

## Questions:
1. Would an increase in the number of "chromosomes"/contigs result in such a drop in performance? If so, what would you recommend? I would rather not remove the scaffolds. The ERCC spike-ins are important to help assess the "truth" by comparing how the different approaches (directional/adjacency/cluster/percentile/unique) correlate with the known concentrations, particularly relative to the original alignments containing duplicates.

2. Do you think it is useful (accuracy and/or speed) for your algorithm to know the identity of the UMI *a priori*? Particularly considering the following properties:
 + long-ish (8nts)
 + 9216 possible combination (96 UMI one on each pair) 

I am stuck at this step and need to perform the deduplication before moving forward with downstream analysis. Any help would be greatly appreciated. I can provide whatever files you might find useful.

Kind regards,
Neel

**Comment by IanSudbery** [comment]
Hi Neel,

Thanks for the detailed report. I suspect that the problem with the ERCCs is the depth of sequencing over them. The most time consuming part of the process is creating the distance matrix containing the edit distance between each of the UMIs present at each position. As this is an all-by-all comparison, it scales as the number of UMIs squared, as does the memory requirement. Under very high sequencing depths, you are likely to have a lot of UMIs present at a single base, well above the 9216 "real" UMIs. Indeed if all 4^8 possible UMIs were present, the calculation of the distance matrix would require 1.5x10^10 string comparisons, and 2x10^9 items to be remembered.  I doubt that its this extreme in your actual case, this is just what the worst case can be.

I can see how this might cause a slow down on the ERCC contigs, which we might expect to be highly expressed. I'm less clear about the other scaffolds, which I wouldn't have expected to be so highly expressed. 

Perhaps you can send some examples of the mapping on the scaffolds, and we could have a look at it?

In theory, knowing the UMIs would help, but I'm not sure if it can be easily integrated into the code. In some ways the easiest thing to do is just discard any reads that don't match the predefined UMIs.  I'll have to think about it.

**Comment by TomSmithCGAT** [comment]
@nmukherjee UMI-tools was not designed to handle situations where the UMIs are known _a priori_ as in your case.

I agree with @IanSudbery and suggest simply removing any reads which don't match the 9216 'real' UMIs. We could add a `--filter` option to the _extract_ or _dedup_ commands specifically for this purpose. You could then simply use the _unique_ method to remove PCR duplicates. 

The downside of this approach would be that you would remove any molecules where the real UMI was not observed at least once in your sample due to sequencing errors. However, this would only occur in rare cases with low abundance molecules. The advantage of performing the filtering at the _dedup_ step is that for each position we could count the removed reads which are :

1. Within 2 edit distancusing the various _dedup_ methods with no filtering. e of an observed real UMI which was observed (e.g sequence errors) = removed read but moleusing the various _dedup_ methods with no filtering. cule retained
2. Not within 2 edit distance of an observed real UMI but within 2 edit distance of an unobserved real UMI = removed read and molecule removed

Providing the vast majority of reads fall into category 1, this would then give you peace of mind that the filtering approach was appropriate. 

As you say, the ERCCs are a useful addition for checking the analysis. I'd recommend comparing the ERCC log counts vs. log concentration when filtering as described above and when using the various _dedup_ methods with no filtering. 

If you'd be happy to share the chr19 BAM I can take a look at the run time issues and implement a --filter option

**Comment by TomSmithCGAT** [comment]
@nmukherjee Have you re-tried this with the latest version? We were getting very long run times in specific cases which have been resolved.

Did you find any other software which was more suitable for your analysis?

**Comment by nmukherjee** [comment]
I am so sorry for not replying earlier...things have been quite busy. I will retry with the latest version and get back to you. For now I simply excluded ERCCs/Scaffolds. One extra tidbit: the slow run time (in the older version) seems to only be the case for paired-end reads on ERCCs or scaffolds. Single-end reads ran just fine. Anyway, will get back to you in soon.

**Comment by TomSmithCGAT** [comment]
Hi @nmukherjee - Just to let you know we have released v0.5 with further improvements to run-time. We'd be interested to hear whether this solves this issue?

**Comment by nmukherjee** [comment]
Hi @TomSmithCGAT,
Sorry for the delay - I was occupied with trans-atlantic move and setting up my lab!

@kriemo tested this out on my behalf. **Yes the newer versions of UMI-tools have solved the deduplication issue.** 

He can dedup a 50MB bam file that contains 889,892 alignments to ERCCs and rRNAs in ~70 seconds with v.4.4 or v0.5.0. If he uses v0.2.3 then the dedup step will not complete after 50+ minutes. 

Thanks so much!

**Comment by TomSmithCGAT** [comment]
Hi @nmukherjee. Don't worry about the delay - sounds like you've had plenty to keep you occupied! Very glad to hear the latest version has resolved the run time issues.

Best of luck with the new lab!
