### ISSUE TITLE
UMI-tools duplicated removal

### ISSUE THREAD

**Issue by mwylerCH** [CGATOxford/UMI-tools#639]
Dear authors, dear IanSudbery,
I'm using you tool and I'm quite happy, many thanks for developing it. However, by browsing around I found the following comment 
```
...it only marks read 1 in a pair. When marking but not removing duplicates, both reads in a pair should be tagged and the bitflags properly set.
```
(source https://github.com/samtools/samtools/issues/1514#issuecomment-986005422)

No my question: is UMI tools removing both reads if duplicated (in paired experiments)? Or only one? What's about with marking? Because my BAM files contain less reads then the pre-UMI_tool processed BAMs, until now I guessed everything was fine.
Sure that this will not take a lot of effort
Greetings

**Comment by IanSudbery** [comment]
I'm not sure what the author of this comment is talking about:

We do not offer a duplicate marking mode. We have two options: Deduplicating, ie removing the duplicates (run with `umi_tools dedup`), or grouping mode (run with `umi_tools group`). 

`dedup` removes both pairs in a read if the we decide the pair is a duplicate. This is feasible because we only remember which reads we keep, which is usually a minority.

`group` only adds grouping information to read1. This is because the memory requirements for remembering the grouping information for all reads is unreasonable in most cases.

**Comment by mwylerCH** [comment]
Perfect, many thanks for the quickly replying. I will close the issue
