### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/UMI-tools#7]
I get an error when I follow the usage in the documentation for dedup.py.

`cat infile.bam | python dedup_umi.py > deduped.bam 2> deduped.log`

`ValueError: fetch called on bamfile without index`

Presumably, this is because pysam uses the filename to obtain the index? If so, is it possible to read from the stdin and pipe to dedup_umi.py? 

I've removed this usage suggestion from the documentation for the time being.

**Comment by IanSudbery** [comment]
Hmmmm… which fetch is it that is causing these problems? You should be able
to fetch as long as you don’t call for a particular region I thought. I
wonder if its your feature detection that’s the problem? That reminds me –
this is going to consume reads isn’t it? Not so good if is on the stidin
anyway.



The piping from stdin will probably work if the input is sam, but probably
best to stick with specifying the input for now.



*From:* Tom Smith [mailto:notifications@github.com]
*Sent:* 14 August 2015 15:52
*To:* CGATOxford/UMI-tools
*Cc:* Ian Sudbery
*Subject:* [UMI-tools] index error (#7)



I get an error when I follow the usage in the documentation for dedup.py.

cat infile.bam | python dedup_umi.py > deduped.bam 2> deduped.log

ValueError: fetch called on bamfile without index

Presumably, this is because pysam uses the filename to obtain the index? If
so, is it possible to read from the stdin and pipe to dedup_umi.py?

I've removed this usage suggestion from the documentation for the time
being.

—
Reply to this email directly or view it on GitHub
<https://github.com/CGATOxford/UMI-tools/issues/7>.[image: Image removed by
sender.]

**Comment by TomSmithCGAT** [comment]
It's the one inside get_bundles (line 429). I'll leave it out of the documentation then. Cheers

**Comment by IanSudbery** [comment]
Okay. I was going to allow the use of SAM files on the input, but I can’t
work out how to work around your detection method checking, so I’ve made it
raise an error if an attempt to use standard in is made.



What does the line:

sum.bam_features.values() == 0



Where is the object “sum” from?



Ian









*From:* Tom Smith [mailto:notifications@github.com]
*Sent:* 14 August 2015 16:07
*To:* CGATOxford/UMI-tools
*Cc:* Ian Sudbery
*Subject:* Re: [UMI-tools] index error (#7)



It's the one inside get_bundles (line 429). I'll leave it out of the
documentation then. Cheers

—
Reply to this email directly or view it on GitHub
<https://github.com/CGATOxford/UMI-tools/issues/7#issuecomment-131140471>.

**Comment by TomSmithCGAT** [comment]
Oops, should be sum(bam_features.values()) == 0. I'll change that now.

Not sure how that one slipped through? We should build in some regression tests!
